### PR TITLE
Update token image for Prosper (PROS)

### PR DESCRIPTION
**Pull request by prosper-fi**
Directed by MetaMask support team to submit a PR here to update the token image that currently shows up on MetaMask for the PROS token.

The token is on both Ethereum and BSC. This PR updates the image and adds an entry for the ETH contract address.

Project website here: https://www.prosper-fi.com/

CoinGecko link here: https://www.coingecko.com/en/coins/prosper

Etherscan link here: https://etherscan.io/address/0x8642a849d0dcb7a15a974794668adcfbe4794b56

Thank you for your help! Please let us know if you have any questions.

### CODE REVIEW

**Comment by prosper-fi** [comment]
@MRabenda Here is the ETH request per your comment on the other (now closed) PR.

Also, before we submit for BSC, could you please help confirm if we are supposed to follow the same procedure and add an entry to the same contract-map.json file but just with the BSC address? Or is it a different procedure?

**Review by Skate-Cloud — APPROVED** [review]

**Comment by prosper-fi** [comment]
@MRabenda just quickly following up on this. Thank you!

**Review by MRabenda — APPROVED** [review]

**Comment by prosper-fi** [comment]
Thank you @MRabenda ! Could you please also confirm the procedure for updating BSC side as well?

**Comment by MRabenda** [comment]
At this time that repo handles on Ethereum network - for BSC it will need to be added to three lists like:

uniswapLabs: 'https://gateway.ipfs.io/ipns/tokens.uniswap.org',
sushiswap: 'https://token-list.sushi.com/',
apeswap: 'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/lists/apeswap.json',

**Comment by prosper-fi** [comment]
@MRabenda thank you! We'll work on getting the BSC version updated on those lists. Once that's done, what would be the next step to ensure that the token logo is updated on MetaMask?

Also, just following up on the ETH side—seems like the image has been updated, however, it's grayscale / B&W: https://static.cx.metamask.io/api/v1/tokenIcons/1/0x8642a849d0dcb7a15a974794668adcfbe4794b56.png. Could you please help fix?

**Comment by prosper-fi** [comment]
Hi @MRabenda , could you please help advise on next steps for the BSC update (as well as the ETH side grayscale token image issue)?

On BSC side, PROS is already on several lists, including PancakeSwap, Rango, CoinGecko, and CoinMarketCap. In all of these cases, the token logo image is already updated to our latest token logo. How do we now ensure that MetaMask will also reflect the correct logo on BSC side?

Thank yoU!

**Comment by prosper-fi** [comment]
Hi @MRabenda , just a quick follow-up on the above. Thanks!

**Comment by prosper-fi** [comment]
Hi @MRabenda , happy new year! Just following up on our conversation above. Thanks!

**Comment by MRabenda** [comment]
Hey @prosper-fi - which MM version are you using?

**Comment by prosper-fi** [comment]
Hi @MRabenda , I think we can just leave it as is at this point. We've actually upgraded our token to a new contract. We will submit a new PR shortly to get the new contract address added!

**Pull request merged**
