### PR TITLE
Add GPO to Metamask contract map

### PR DESCRIPTION
**Pull request by deAngelisAlex**
To whom it may concern,

I'm Alexandre de Angelis (@deAngelisAlex), Head of Engineering on the GoldPesa project (https://goldpesa.com), and I would like to hereby submit a PR to add our token to the Metamask's list of known tokens + logos.

Link to our Etherscan: https://etherscan.io/token/0x4ad7a056191f4c9519facd6d75fa94ca26003ace
You will find below the information about the project, which is public information on our website, CoinGecko and CoinMarketCap:
_____________
**What Is GoldPesa Option (GPO)?**

The GoldPesa Option token is an exotic option with a moving strike price. Each $GPO token represents an option to purchase 1 GoldPesa ($GPX) token in Phase 2 at spot gold price + 1%.

**What Is GoldPesa (GPX)?**

GoldPesa (“GPX”), a tokenised gold-backed structured product created using innovative financial engineering and quantitative science.

GPX is a unique asset-backed hybrid token whereby one token is backed by one gram of a physical gold, stored in secure vaults.

GPX gives customers the benefits of physical ownership with the speed and mobility of a digital asset. In addition token holders are able to have fractional ownership of physical bars and the upside of the crypto markets which makes GPX a hybrid gold-backed token with upside and NOT a stable coin.

**How Can A Gold-Backed Token Trade At A Premium?**

GoldPesa invests 50% of all fees in a brokerage account managed by the PAWN, a proprietary and highly intelligent trading algorithm.

Profits generated by the PAWN are used to buy back and then burn GPX tokens from the market, which rewards token holders by creating demand and reducing supply at the same time.

This model effectively creates an earnings to an asset class (gold) that generally does not have any earnings and as a result gives the token an intrinsic value. Based on traditional finance, by creating earnings, we can expect the market to trade GPX at some multiple of the earnings and therefore will result in GPX being traded at a premium depending on the performance of our proprietary and highly intelligent trading algorithm.

It's important to note that GPX token holder's gold remains unencumbered at all times as we risk our own capital for the benefit of GPX holders, resulting in a token which has the characteristics of a DeFi gold-backed structured product.

As GPX begins to trade at a premium, the intrinsic value of the GoldPesa Option token (GPO) will also increase naturally as it would be correlated to the premium of GPX.

**The GoldPesa Project Is Being Launched In 3 Phases:**

Phase 1: Launch GoldPesa Option (GPO) : Release 100M GoldPesa Option ($GPO) tokens. Each $GPO token represents an option to purchase 1 GoldPesa ($GPX) token in Phase 2 at spot gold price + 1%.

Phase 2: Launch GoldPesa Token (GPX) : Launch GoldPesa DEX, enabling $GPO holders to purchase $GPX at spot gold price + 1%. $GPX tokens are minted in real-time and delivered to your wallet.

Phase 3: Release GoldPesa Token (GPX) : List $GPX on major centralized and decentralized exchanges whereby the intrinsic value of $GPX = 1 gram pure gold + profit generated by the PAWN!

How many GPO tokens are there in circulation?

GPO launched on the Ethereum MainNet on Oct 12, 2021 with a hard cap of 100 million GPO tokens created at genesis. GPO also has a wallet hard cap of 100,000 GPO per wallet.

Who Are The Founders Of GoldPesa?

GoldPesa is the brainchild of developer and computer engineer Shamik Raja who has extensive experience in digital signal processing, programming, commodities and quantitative science.

Between 2001 and 2006, Raja earned a degree in Electrical & Computer Engineering from the University of British Columbia in Canada. Over the years Raja has focused on research involving the application of principals in digital signal processing to create an automated commodity-buying system that uses algorithmic calculations to navigate complex international commodity and currency markets.

GoldPesa is an amalgamation of Raja’s 8 years experience in the precious metals sector combined with over 20 years experience in quantitative science and engineering.

**Where Can I Buy GPO?**

GPO can be purchased on the GoldPesa decentralized exchange power by Uniswap.

GoldPesa has coded an advanced dynamic liquidity protocol, using Uniswap V3. The code places liquidity in concentrated ranges which rebalance automatically based on machine learning models, resulting in steady growth, price protection and lower slippage.
______________

Kind regards,
deAngelisAlex

### CODE REVIEW

**Comment by deAngelisAlex** [comment]
Hi @MRabenda,

Could you kindly explain what the "pending community activity" label means? 

Kind regards

**Comment by trastvolt** [comment]
GoldPesa:master

**Review by MRabenda — APPROVED** [review]

**Comment by MRabenda** [comment]
@deAngelisAlex looks like we are good to merge. Can you please solve conflicts?

**Comment by deAngelisAlex** [comment]
Done! Thank you!

**Comment by MRabenda** [comment]
@deAngelisAlex GPO decimals is 16 or 18 https://etherscan.io/address/0x4ad7a056191f4c9519facd6d75fa94ca26003ace#readContract ?

**Comment by deAngelisAlex** [comment]
> @deAngelisAlex GPO decimals is 16 or 18 https://etherscan.io/address/0x4ad7a056191f4c9519facd6d75fa94ca26003ace#readContract ?

Hi! It's 18.

**Pull request merged**
