### PR TITLE
🐱 add support for MEOW ERC20 token icon

### PR DESCRIPTION
**Pull request by smolgroot**
A PR to add the MEOW token icon.

- Contract address (Ethereum mainnet): 0x77be1ba1Cd2D7a63BFfC772D361168cc327dd8bc
- Website: https://meoweth.com/
- Etherscan (contract verified): https://etherscan.io/token/0x77be1ba1cd2d7a63bffc772d361168cc327dd8bc

You can also find our project here:

- CMC: https://coinmarketcap.com/currencies/miaomiaomiaoerc20/
- CoinGecko: https://www.coingecko.com/en/coins/meow

### CODE REVIEW

**Review by MRabenda — APPROVED** [review]

**Review by MRabenda — CHANGES_REQUESTED** [review]
1. Based on the current contract state I can read that this contract decimals i 9 not 18
2. Is there any chance that this 1MB logo would be optimized at any scale? Even few % would be nice

**Comment by smolgroot** [comment]
OK, good point regarding the decimals.. 
I'm waiting for an optimized logo, I'll push it ASAP.

Thanks

**Comment by smolgroot** [comment]
I've just added an optimized SVG logo and have corrected the contract decimal properly.

**Review by MRabenda — APPROVED** [review]

**Comment by MRabenda** [comment]
Great work, thank you for your contribution

**Pull request merged**
