### PR TITLE
add_CR

### PR DESCRIPTION
**Pull request by cryptomindex**
Cryptomindex is an easy and safe  trading system in the cryptocurrency industry and Cryptomind is the main coin of Cryptomindex exchange

Website: https://www.cryptomindex.com
 Etherscan: https://etherscan.io/address/0x46576e20EC5F25586A6Fa2E0d6B6058354B72E72
Twitter: https://twitter.com/cryptomindex1
Linkedin: https://linkedin.com/company/cryptomindex/

### CODE REVIEW

**Comment by xrn** [comment]
HI @cryptomindex - regular svg icon has ~ 5Kb - this one has over 60kB could you try to optimize it?

**Comment by cryptomindex** [comment]
@xrn  Now the logo has ~10KB. I used different tools, but I was able to reduce the size as much. Is this enough?

**Review by xrn — APPROVED** [review]

**Comment by cryptomindex** [comment]
Thanks, How many days does it take for a new token to be added to Metamsk?

**Comment by xrn** [comment]
I am expecting ~ 2 weeks - it requires to be released as repo and then included to new MM release

**Pull request merged**
