### PR TITLE
Add PARSIQ (PRQ)

### PR DESCRIPTION
**Pull request by Daniel-PARSIQ**
PARSIQ is a next-generation platform for monitoring and intelligence — offering analytics tools for blockchain technology across a plethora of industries. This enables users to track network activity in real time, unlock new use cases for their application and create instant notifications. Smart Triggers can be used to react to events of interest on multiple networks.

Website: https://www.parsiq.net/en/
 Etherscan: https://etherscan.io/address/0x362bc847a3a9637d3af6624eec853618a43ed7d2
CoinGecko: https://www.coingecko.com/en/coins/parsiq
CoinMarketCap: https://coinmarketcap.com/currencies/parsiq/
Twitter: https://twitter.com/parsiq_net
Medium: https://parsiq.medium.com/

### CODE REVIEW

**Comment by xrn** [comment]
Hi @Daniel-PARSIQ thanks for contribution - can you check your svg image - looks like it is broken

**Comment by xrn** [comment]
Hi when I am going to Files changed -> SVG file -> 3 dots -> view file  I still can not see logo

**Comment by xrn** [comment]
@Daniel-PARSIQ SVG is working now - can you remove from this PR not used SVG image file?

**Comment by Daniel-PARSIQ** [comment]
I've uploaded a new svg and removed the ones that didn't work. I exported my svg from photoshop, it works on my computer, I have no idea why it doesn't work on GitHub.

Thanks for the feedback

**Review by xrn — APPROVED** [review]

**Pull request merged**
