### PR TITLE
Added Fasttoken

### PR DESCRIPTION
**Pull request by fasttoken1**
Token Name - Fasttoken
Contract Address -  0xaeDf386B755465871fF874E3E37Af5976E247064
Whitepaper - https://docs.fasttoken.com/fasttoken-official-whitepaper.pdf
Etherscan link - https://etherscan.io/token/0xaedf386b755465871ff874e3e37af5976e247064
Website - https://www.fasttoken.com/

### CODE REVIEW

**Comment by SurenFTN** [comment]
@MRabenda  what is the flow of Approving this merge request.

Sincerely Suren K.

**Comment by MRabenda** [comment]
Number of Holders and Transfers have to be bigger

**Comment by fasttoken1** [comment]
Hi @MRabenda. The number of holders and transfers is much bigger now, so it's time to merge the PR with master.

**Comment by MRabenda** [comment]
Hey @fasttoken1 - thanks for your patience, you are right we are ready to go. But before that - you have to fix your json it is missing decimals and closing bracket

**Comment by fasttoken1** [comment]
Thanks for the feedback! We fixed it.

**Review by MRabenda — APPROVED** [review]

**Pull request merged**
