### PR TITLE
Add GIGX logo and token

### PR DESCRIPTION
**Pull request by gigxcoin**
Token Address : 0xf74d5B5A806BF8904337C1738C1583279ba0e27c
Token Name: GIGX COIN
Token Decimals: 18
Token Symbol: GIGX

Etherscan: https://etherscan.io/token/0xf74d5B5A806BF8904337C1738C1583279ba0e27c
Twitter: https://twitter.com/GigXCoin_ICO
Discord: https://discord.gg/wSrU2cHe
Telegram: https://t.me/+KBNZenOFkx1mYTI9
Website: https://gigxcoin.net

### CODE REVIEW

**Comment by MRabenda** [comment]
SVG image is required

**Comment by gigxcoin** [comment]
> SVG image is required

Hello MRabenda, 

Thanks for the response.

The SVG file is in the second commit 8f45a90.

**Comment by MRabenda** [comment]
You have to update ten JSON to reflect it ` "logo": "GIGX.png",`

**Comment by gigxcoin** [comment]
> You have to update ten JSON to reflect it ` "logo": "GIGX.png",`

The JSON file has now been updated. Thanks for the check.

**Comment by MRabenda** [comment]
Token not active

**Pull request closed without merging**
