### PR TITLE
Add keyTango Token (TANGO)

### PR DESCRIPTION
**Pull request by trnhgquan**
Token address: 0x182F4c4C97cd1c24E1Df8FC4c053E5C47bf53Bef
Token name: keyTango Token
Token symbol: TANGO
Token decimals: 18
Website: https://keytango.io/
Twitter: https://twitter.com/TangoKey
Etherscan: https://etherscan.io/token/0x182F4c4C97cd1c24E1Df8FC4c053E5C47bf53Bef

### CODE REVIEW

**Comment by xrn** [comment]
Hi, 

@trnhgquan can you please:
1. Remove changes from others files than contract-map.json 
2. Remove png file and use svg logo?

**Comment by trnhgquan** [comment]
Hi @xrn , 

Just remove unused file and update logo as svg.

Thanks.

**Review by xrn — APPROVED** [review]

**Comment by xrn** [comment]
We are good to go - but you have to solve conflicts

**Comment by trnhgquan** [comment]
Hi @xrn , 

Solved conflict.

Thanks.

**Pull request merged**
