### PR TITLE
add token logo Africash 

### PR DESCRIPTION
**Pull request by mantogo**
add token logo Africash

### CODE REVIEW

**Comment by MRabenda** [comment]
1. On which chain this token is deployed?
2. Can you remove png file from the PR?
3. Can you please fix json file to do not remove existing assets?

**Comment by mantogo** [comment]
hello 

please is there anything else i can do?

**Comment by mantogo** [comment]
> hello
> 
> please is there anything else i can do?

should I close the pr please and start a new one?

**Comment by MRabenda** [comment]
You have to fix PR - you can do this in a current one, or open new one if you prefer

**Comment by mantogo** [comment]
ok im going to open a new one witch will include svg logo now

**Comment by mantogo** [comment]
done. new one created

**Comment by mantogo** [comment]
close

**Pull request closed without merging**
