### PR TITLE
added perion credits

### PR DESCRIPTION
**Pull request by Jett19672**

### CODE REVIEW

**Review by MRabenda — APPROVED** [review]

**Comment by Jett19672** [comment]
Hey @MRabenda How long does it usually take for the UI to get a bump and the token to start showing?

**Comment by MRabenda** [comment]
2-4 weeks at maximum

**Comment by Jett19672** [comment]
Hey @MRabenda, it has been almost 6 weeks now; looking to get an update on that one if possible. Thanks so much and really appreciate the work you guys are doing for the space.

**Comment by Jett19672** [comment]
Hey, @MRabenda I am following up on this again as I have not received a response in over a month. Any chance we could get an update on this one?

**Comment by MRabenda** [comment]
Our repo has a realase https://github.com/MetaMask/contract-metadata/releases/tag/v2.3.1 few days ago. Your logo has been included an new version is added to MM code. New soon new version of extension/mobile app should include your logo

**Comment by Jett19672** [comment]
Hey, the extension and mobile app got updated but still does not include the Perion logo? @MRabenda

**Comment by Jett19672** [comment]
Hey @MRabenda, thank you so much for getting Perion added to the desktop app but can we by any chance, be added to the mobile version too?

**Comment by Jett19672** [comment]
Hey @MRabenda, I have just checked the mobile version of PERC and it seems like we have had the wrong logo placed on the app, as well as a verification error showing as depicted here.
image (12)

Thank you, looking forward to your reply.

**Comment by Jett19672** [comment]
Hey @MRabenda, following up on the above as I have not heard back. Thank you

**Comment by Jett19672** [comment]
Hey @MRabenda, I am following up for the final time as we have not had a response, are you receiving the notifications?

**Comment by Jett19672** [comment]
Otherwise will escalate if no response in 24 hours.

**Comment by MRabenda** [comment]
Hey @Jett19672 - sorry for the late response, it looks like now the token is auto-detected. Can you confirm that your problem is solved?

**Comment by Jett19672** [comment]
It is auto-detecting but is not the same logo as the desktop version. Could you change the logo on Mobile?

**Comment by cloudonshore** [comment]
Screenshot 2023-07-06 at 1 11 52 AM
Screenshot 2023-07-06 at 1 11 52 AM
I believe this issue has been resolved, I'm seeing the same Icon on both mobile and extension @Jett19672

**Pull request merged**
