### PR TITLE
Add Reflect Finance

### PR DESCRIPTION
**Pull request by CaptainStake**
reflect.finance (RFI) is an innovative Ethereum token that re-imagines the concept of DeFi yield generation
WEB: https://reflect.finance/
ETHERSCAN: https://etherscan.io/token/0xa1afffe3f4d611d252010e3eaf6f4d77088b0cd7
GITHUB: https://github.com/reflectfinance
MEDIUM: https://reflectfinance.medium.com/
TWITTER: https://twitter.com/ReflectFinance
TELEGRAM: https://t.me/reflect_finance
COINGECKO: https://www.coingecko.com/en/coins/reflect-finance

### CODE REVIEW

**Comment by xrn** [comment]
Hi @CaptainStake  - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

Also, there is the requirement that the address has to follow the EIP-55 format

**Comment by CaptainStake** [comment]
Hi @xrn thanks for your time on this I have added the SVG & updated the contact-map.json do you need anything else?

Thank you

**Comment by xrn** [comment]
@CaptainStake address is still not EIP-55 format :)

**Comment by CaptainStake** [comment]
@xrn apologies, please see update, is that correct?

**Review by xrn — APPROVED** [review]

**Comment by CaptainStake** [comment]
@xrn thank you for your help and advice. Have a good new year, quick question how long does this data take to pull through to the front end on metamask in your experience?

**Comment by xrn** [comment]
RFI has to be included in the new release of this repository and then in the new release of MetaMask - it can take the next 2-3 weeks.

**Pull request merged**
