### PR TITLE
Add icons for OGV, veOGV and wOUSD

### PR DESCRIPTION
**Pull request by rolandpo**
This adds icons for OGV, veOGV and wOUSD tokens, created by Origin Protocol.
Origin Protocol already has 2 tokens included in MetaMask, OGN and OUSD, a rebasing stablecoin with a $65M market cap.

OGV is the new governance token for OUSD
Etherscan: https://etherscan.io/address/0x9c354503C38481a7A7a51629142963F98eCC12D0

veOGV is the vote escrowed version of OGV, representing locked up governance tokens
Etherscan: https://etherscan.io/address/0x0C4576Ca1c365868E162554AF8e385dc3e7C66D9

wOUSD is a non-rebasing version of OUSD, a tokenized vault that appreciates in value instead of growing in number
Etherscan: https://etherscan.io/address/0xD2af830E8CBdFed6CC11Bab697bB25496ed6FA62

Origin Protocol website: https://www.originprotocol.com/
Blog: https://medium.com/originprotocol
OUSD Dapp: https://ousd.com/
OUSD address registry: https://docs.ousd.com/smart-contracts/registry
More about new governance tokens and mechanism: https://blog.originprotocol.com/tokenomics-retroactive-rewards-and-prelaunch-liquidity-mining-campaign-for-ogv-1b20b8ab41c8

### CODE REVIEW

**Comment by joshfraser** [comment]
For added context on the community engagement requirement, it's worth noting that OGV is going to be [airdropped](https://blog.originprotocol.com/hello-ogv-details-on-the-upcoming-airdrop-for-ogn-holders-2660dab47757) to the [41k holders of OGN](https://etherscan.io/token/0x8207c1ffc5b6804f6024322ccf34f29c3541ae26) on July 12th. The launch of OGV has also already gained support from over a [dozen top exchanges](https://blog.originprotocol.com/exchanges-supporting-origins-upcoming-ogv-launch-b4a6d1214d9c) including Binance, Huobi, Gate, and KuCoin. It would be great if we could get this merged before the 12th given how many people will be holding OGV at that point. 

CC: @danfinlay & @owocki who have been a great help with this sort of thing in the past. 🙏

**Comment by MRabenda** [comment]
0xFdb16A6900Ce90Cb27Afec95dc274D27E0d61b87 <- I can not confirm that this is ERC type of contract using the Etherscan. Seems that 2 others are.

**Comment by rolandpo** [comment]
Sorry about that, the proxy address for veOGV was pointing to an outdated contract. The proxy itself has been changed in the meantime and I've updated the contract map and the comment above to reflect this, thanks!

Etherscan veOGV link: https://etherscan.io/address/0x0C4576Ca1c365868E162554AF8e385dc3e7C66D9

**Comment by rolandpo** [comment]
Hi @MRabenda, I've removed wOUSD from the PR. On the topic of community activity, the OGV airdrop has started with over 500 holders for both OGV and veOGV and over 4000 OGV transfers at the time of writing, with more to come before the claiming process ends. Hoping this could now get merged with all the criteria met, thanks for your help!

**Review by MRabenda — APPROVED** [review]

**Comment by micahalcorn** [comment]
Thanks, @MRabenda 🙏 Are these changes live or do they depend on a deployment or new release?

**Comment by MRabenda** [comment]
After release of this repo and new MM version

**Pull request merged**
