### PR TITLE
Add Kromatika Token

### PR DESCRIPTION
**Pull request by sNnickK**
https://etherscan.io/token/0x3af33bef05c2dcb3c7288b77fe1c8d2aeba4d789
https://coinmarketcap.com/currencies/kromatika/
https://info.uniswap.org/#/tokens/0x3af33bef05c2dcb3c7288b77fe1c8d2aeba4d789

### CODE REVIEW

**Comment by sNnickK** [comment]
Hello David, XRN. Would you like to approve KROM ?

**Comment by xrn** [comment]
hi @sNnickK 

1. Address has to be in EIP-55 format
2. SVG logo < 10kB size is a requirement, please replace PNG one

**Comment by sNnickK** [comment]
@xrn Everything fixed

**Comment by xrn** [comment]
Hi @sNnickK - thanks for the updates

1. Can you remove png file from PR?
2. Your image has > 200kB and poor quality - regular SVG logo should have < 10kB and be a vector file. Could you try to fix it?

**Comment by sNnickK** [comment]
> Hi @sNnickK - thanks for the updates
> 
> 1. Can you remove png file from PR?
> 2. Your image has > 200kB and poor quality - regular SVG logo should have < 10kB and be a vector file. Could you try to fix it?

Check it now

**Comment by xrn** [comment]
@sNnickK this is still PNG image encoded in base64 not vector one - any chance for such a beautiful logo to be provided in vector SVG format?

**Comment by sNnickK** [comment]
> @sNnickK this is still PNG image encoded in base64 not vector one - any chance for such a beautiful logo to be provided in vector SVG format?

We dont have .svg format only PNG. :/

**Comment by sNnickK** [comment]
@xrn Wait for our new rebranded logo, ill send it to you in svg format.

**Comment by xrn** [comment]
Hi @sNnickK - your SVG file has still > 150kB which is much to big and I am not able to see this file, like it is broken.

**Comment by sNnickK** [comment]
Here it is uploading now. 

>

**Comment by sNnickK** [comment]
@xrn Logo updated, you can marge.

**Review by xrn — APPROVED** [review]

**Comment by xrn** [comment]
Looks great - I love your new logo. Thanks for your contribution

**Pull request merged**
