### PR TITLE
add SORA tokens: XSTUSD, PSWAP, XOR, VAL

### PR DESCRIPTION
**Pull request by tarmovannas**
Website https://sora.org
Website https://polkaswap.io

Github https://github.com/sora-xor

Twitter https://twitter.com/sora_xor
Twitter https://twitter.com/polkaswap

Medium https://medium.com/sora-xor
Medium https://medium.com/polkaswap

Youtube https://youtube.com/sora_xor
Youtube https://youtube.com/polkaswap

Instagram https://instagram.com/sora_xor
Instagram https://instagram.com/polkaswap

Telegram https://t.me/sora_xor
Telegram https://t.me/polkaswap

Reddit https://reddit.com/r/SORA
Reddit https://reddit.com/r/Polkaswap

**SORA Synthetic USD (XSTUSD)**
Etherscan https://etherscan.io/token/0xc7d9c108d4e1dd1484d3e2568d7f74bfd763d356
CoinGecko https://www.coingecko.com/en/coins/sora-synthetic-usd (expected URL)

**Polkaswap (PSWAP)**
Etherscan https://etherscan.io/token/0x519c1001d550c0a1dae7d1fc220f7d14c2a521bb
CoinGecko https://www.coingecko.com/en/coins/polkaswap

**SORA (XOR)**
Etherscan https://etherscan.io/token/0x40FD72257597aA14C7231A7B1aaa29Fce868F677
CoinGecko https://www.coingecko.com/en/coins/sora

**SORA Validator (VAL)**
Etherscan https://etherscan.io/token/0xe88f8313e61A97cEc1871EE37fBbe2a8bf3ed1E4
CoinGecko https://www.coingecko.com/en/coins/sora-validator-token

### CODE REVIEW

**Comment by xrn** [comment]
@tarmovannas 

1. Can you replace sora-val.png with SVG version?
2. Can you remove "val.svg" and "xor.svg" files?

**Comment by tarmovannas** [comment]
> 1. Can you replace sora-val.png with SVG version?

Unfortunately, not really. The logo is meant to look like realistic gold, it would result in a very large file as a vector image and still not look good enough.

> 2. Can you remove "val.svg" and "xor.svg" files?

**Done**

**Comment by xrn** [comment]
@tarmovannas SVG image is requirement for merge

**Comment by tarmovannas** [comment]
@xrn added sora-val.svg (removed sora-val.png), and fixed conflicts, should be ready to merge if you can approve, thanks

**Review by xrn — APPROVED** [review]

**Comment by xrn** [comment]
@tarmovannas thanks a lot. All addresses should be in EIP-55 format

**Comment by tarmovannas** [comment]
> All addresses should be in EIP-55 format

thanks. fixed it. @xrn

**Pull request merged**
