### PR TITLE
Add Mindsync MAI token

### PR DESCRIPTION
**Pull request by mindsync-dev**
Website: https://mindsync.ai/
Telegram: https://t.me/mindsyncai
Etherscan: https://etherscan.io/token/0x75387e1287Dd85482aB66102DA9f6577E027f609
Token Address: 0x75387e1287Dd85482aB66102DA9f6577E027f609
Token Symbol: MAI

### CODE REVIEW

**Comment by xrn** [comment]
Hi @mindsync-dev  - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

**Comment by mindsync-dev** [comment]
Hi, surely, thank you

**Comment by mindsync-dev** [comment]
Unfortunately I'm not able to make the SVG size below 49K

**Comment by xrn** [comment]
For such a simple (but beautiful)  logo it should be doable to make it even ~ 1Kb - Can you please solve conflicts?

**Comment by mindsync-dev** [comment]
We remade the logo svg file, for now 2.2Kb

**Comment by xrn** [comment]
Please solve conflicts and we are rdy to go

**Review by xrn — APPROVED** [review]

**Pull request merged**
