### PR TITLE
added CTX and TCAP tokens

### PR DESCRIPTION
**Pull request by crisgarner**
Website is https://cryptex.finance
Token address can be confirmed on coingecko also:
https://www.coingecko.com/en/coins/tcap
https://www.coingecko.com/en/coins/ctx 

TCAP is a fully decentralized ERC-20 compatible smart contract that tokenizes real-time Total Market Capitalization from ALL cryptocurrencies and tokens listed on the largest crypto data providers in the world, created by Cryptex Finance.

CTX is the governance token of the Cryptex Protocol.

### CODE REVIEW

**Review by prestonvanloon — APPROVED** [review]

**Comment by MRabenda** [comment]
@crisgarner can you solve conflicts and change name of tcap to TCAP Token in a same way as contract is returning it via ABI? I am happy to merge this PR

**Comment by crisgarner** [comment]
Hey sure, I can fix it

**Comment by crisgarner** [comment]
Done @MRabenda

**Review by MRabenda — APPROVED** [review]

**Comment by MRabenda** [comment]
In TCAP you are missing deciamls field and }

**Comment by crisgarner** [comment]
> In TCAP you are missing deciamls field and }

Sorry about that, used the online tool. It should be fixed now

**Pull request merged**
