### PR TITLE
Please Add ELTCOIN

### PR DESCRIPTION
**Pull request by Steake**
# ELTCOIN
_Ethereum Limited Total Coin_
--
Please list the ELTCOIN token we are an old and verified community currency with active daily community of traders and holders; please see below our credentials:

✅ [Etherscan Token Page](https://etherscan.io/token/0x44197A4c44D6A059297cAf6be4F7e172BD56Caaf)
✅ [Etherscan Contract Source Code Verified _(Exact Match)_](https://etherscan.io/address/0x44197A4c44D6A059297cAf6be4F7e172BD56Caaf#code)
✅ [CoinMarketCap](https://coinmarketcap.com/currencies/ELTCOIN/)
✅ [CoinGecko](https://www.coingecko.com/en/coins/eltcoin)
✅ [Website](https://eltcoin.tech)
✅ [Twitter](https://twitter.com/officialELTCOIN) 
✅ [Telegram](https://t.me/ELTCOIN) ⬅️ **Main Community**
✅ [Reddit](https://www.reddit.com/r/eLTCoin/)
✅ [Instagram](https://www.instagram.com/moonlambos/) 😝
✅ [GitHub](https://github.com/ELTCOIN/) 

https://user-images.githubusercontent.com/530040/102751484-6a289080-439a-11eb-8c7b-dbc612071449.mp4

### CODE REVIEW

**Comment by xrn** [comment]
@Steake - `0x6781a0F84c7E9e846DCb84A9a5bd49333067b104` probably is not address of eltcoin

**Comment by Steake** [comment]
> @Steake - `0x6781a0F84c7E9e846DCb84A9a5bd49333067b104` probably is not address of eltcoin

You are quite right, how did i manage to make such a stupid error 😅

**Comment by xrn** [comment]
@Steake thanks for fix. Is there any change for smaller logo than 256KB? ELTCOIN logotype is pretty simple - are you able to use smaller SVG file?

**Review by Steake — COMMENTED** [review]
Consideribly reduced the logo svg footprint 😉

**Review by xrn — APPROVED** [review]

**Pull request merged**
