### PR TITLE
added EscoCoin Token (#1190)

### PR DESCRIPTION
**Pull request by pablocartel**
Token Website
https://escocoin.com/

Token Contract
https://etherscan.io/token/0x7163436b8EfFfB469F6BB81cc908b1661d4795e6

Token Socials
https://t.me/escocoinofficial
https://twitter.com/escocoin

### CODE REVIEW

**Comment by MRabenda** [comment]
Your image size is pretty big - are you able to improve SVG to reduce it to < 10Kb?

**Comment by pablocartel** [comment]
png will work ?

**Comment by MRabenda** [comment]
No SVG is required - this has to be vector file

**Comment by pablocartel** [comment]
For Price you can use CoinMarketCap link 
https://coinmarketcap.com/currencies/esco-coin/

**Review by MRabenda — APPROVED** [review]

**Comment by pablocartel** [comment]
Thanks for approval how much time will it take to reflect on metamask also what about price ?

**Pull request merged**
