### PR TITLE
Adding Intercoin logo for Intercoin project (ITR)

### PR DESCRIPTION
**Pull request by EGreg**
Home of the Intercoin project: https://intercoin.org
Building a next-gen scalable crypto payment platform.

### CODE REVIEW

**Comment by EGreg** [comment]
Please let us know if we need to do anything else

**Comment by EGreg** [comment]
Just checking in to see if you are able to merge this into the MetaMask repo

**Comment by EGreg** [comment]
Here is the smart contract's address:
0x6Ef5febbD2A56FAb23f18a69d3fB9F4E2A70440B

**Comment by EGreg** [comment]
Just pinging anyone on the project ... @aspiers is there anything else you need u to provide before you can merge this pull request?

**Comment by aspiers** [comment]
I'm not a maintainer, sorry.

**Comment by EGreg** [comment]
@aspiers oh, I apologize. I tagged you because I saw you merged this token pull request 3 days ago, so I figured you could do the same. Please, tell me the procedure. Who would be the right person to reach out to about merging this? @danfinlay or @estebanmino ?

https://github.com/MetaMask/eth-contract-metadata/commits?author=aspiers

**Comment by aspiers** [comment]
@EGreg I didn't merge it, I just submitted the PR and waited patiently :-)  However it seems that somehow mine jumped yours in the queue, so you are probably justified to reach out to the maintainers.

**Comment by EGreg** [comment]
@danfinlay and @estebanmino sorry to bug you guys, can you please tell us what we can do to also be merged? Projects that submitted after us have already been merged :)

**Comment by danfinlay** [comment]
Per [the readme](https://github.com/MetaMask/eth-contract-metadata):

> This repository is effectively frozen. We recommend that developers of new tokens use EIP 747 to ask the user's permission to display your tokens in their wallet. This reduces the dangers of airdrop-based phishing, and reduces administrative overhead from managing this list.

We will revisit this at any time that we have the capacity to evaluate new token submissions.

**Comment by EGreg** [comment]
Thank you. Yes, the 747 is a good idea. I just noticed that @rekmarks approved two tokens 12 days ago, and this AERGO token 11 days ago, and they were submitted after us. So I figured maybe ours can be approved the same way? Would be happy to replace the logo with an SVG if it's necessary.

**Comment by xrn** [comment]
Inactive contract

**Comment by EGreg** [comment]
Hi @xrn can you please clarify what you meant by "inactive contract"?
(I saw that some contracts and tokens are being approved, what do they have that ITR doesn't, and how can we address it?)

**Comment by xrn** [comment]
Hi @EGreg 

1. This pull request in incorrect - there is no JSON changes and icons should be in SVG format
2. On the time when I was closing this PR - there was ~ 10 transactions in last 100 days - this mean from my perspective that the contract is not used by a users

If you think that we should reconsider this contribution - please open new PR with all required details

**Pull request closed without merging**
