### PR TITLE
USDN coin added

### PR DESCRIPTION
**Pull request by vlzhr**

### CODE REVIEW

**Comment by vlzhr** [comment]
Hope this is correct :)

**Comment by xrn** [comment]
@vlzhr thanks look great - can you solve conflicts and we should be able to merge it.

**Comment by vlzhr** [comment]
@xrn conflict solved!

**Comment by vlzhr** [comment]
Could you review it please? @xrn

**Comment by xrn** [comment]
Hi @vlzhr seems like this token has not enough activity to merge yet, I see only 78 holders and ~ 300 transfers. I will make a second review after some time - if the number will go up I am happy to add this token to this repository

**Comment by xrn** [comment]
USDN is already added

**Pull request closed without merging**
