### PR TITLE
Add TRON(TRX) and BitTorrent(BTT) logo

### PR DESCRIPTION
**Pull request by taihaofu**
Add TRON and BitTorrent logo support for ERC20 TRX and BTT token. 

ERC20 TRX and BTT tokens are mapping versions of TRX/BTT from TRON blockchain.  The assets are backed by TRON foundation and BitTorrent.

TRON website: https://tron.network/
BitTorrent website: https://www.bittorrent.com/

TRX address on Ethereum: 0xE1Be5D3f34e89dE342Ee97E6e90D405884dA6c67
BTT address on Ethereum: 0xE83CCCfABD4eD148903Bf36d4283eE7C8b3494D1

### CODE REVIEW

**Comment by xrn** [comment]
hi @taihaofu - BTT logo size is over 1MB we are expecting that logo should have <10kB in SVG format - can you update, please?

**Comment by taihaofu** [comment]
> hi @taihaofu - BTT logo size is over 1MB we are expecting that logo should have <10kB in SVG format - can you update, please?

Done.

**Comment by xrn** [comment]
Thanks @taihaofu but looks like that sth is wrong with this file - https://github.com/MetaMask/contract-metadata/blob/4ce219bb5675e33ddb2e3a6b01872f1231bffebc/images/BTT.svg

**Comment by taihaofu** [comment]
@xrn Thank you for your help! Can you check the image again?

**Comment by xrn** [comment]
Hi @taihaofu - this logo https://github.com/MetaMask/contract-metadata/blob/bf4a7517f8e8e0ee86085e276b49073752a0528d/images/BTT.svg still do not look like correct svg one

**Comment by xrn** [comment]
@taihaofu  @ShawnWu0x here are correct, small (less than 2 kB), responsive SVG logos of these tokens

1. BTT - https://worldvectorlogo.com/logo/btt-bittorrent
2. Tron - https://cryptologos.cc/logos/tron-trx-logo.svg?v=013

Can you release current ones with this?

**Comment by ShawnWu0x** [comment]
> @taihaofu @ShawnWu0x here are correct, small (less than 2 kB), responsive SVG logos of these tokens
> 
> 1. BTT - https://worldvectorlogo.com/logo/btt-bittorrent
> 2. Tron - https://cryptologos.cc/logos/tron-trx-logo.svg?v=013
> 
> Can you release current ones with this?

Thanks @xrn, I've just replaced the files with you provided, please help to review it . Thanks .

**Comment by HoneyCivik** [comment]
Add TRON and BitTorrent logo support for ERC20 TRX and BTT token.

ERC20 TRX and BTT tokens are mapping versions of TRX/BTT from TRON blockchain. The assets are backed by TRON foundation and BitTorrent.

TRON website: https://tron.network/
BitTorrent website: https://www.bittorrent.com/

TRX address on Ethereum: 
TYVwsZQmj9k1Hc4KiUp5DGLNvcWAz1VHQC
BTT address on Ethereum: 
0x5296FE5e8467fbE27Fb048dbE19F3447b3A0e708

**Comment by MRabenda** [comment]
Both contracts migrated

**Pull request closed without merging**
