### PR TITLE
Adding GALA token

### PR DESCRIPTION
**Pull request by ryanml**
Address: `0x15D4c048F83bd7e37d49eA4C83a07267Ec4203dA`
Website: https://gala.games/
Market Info: https://compound.finance/markets/GALA
Etherscan: https://etherscan.io/token/0x15D4c048F83bd7e37d49eA4C83a07267Ec4203dA
Ecosystem Info: https://gogalagames.medium.com/the-gala-games-node-ecosystem-9760d8156af7

Screen Shot 2020-12-25 at 4 09 08 PM
Screen Shot 2020-12-25 at 4 08 47 PM

### CODE REVIEW

**Comment by xrn** [comment]
Hi @ryanml  - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

**Comment by ryanml** [comment]
@xrn Thanks! I've updated the diff with an SVG logo. Should look the same per these screenshots:

Screen Shot 2020-12-29 at 2 53 14 PM
Screen Shot 2020-12-29 at 2 53 26 PM

**Comment by xrn** [comment]
@ryanml looks like it is converted from PNG - quality is low and the size of it is over 100Kb. Is there an option that you will get vector SVG logo - size should be like ~ 1Kb even

**Comment by ryanml** [comment]
@xrn - woops, an oversight on my part, sorry about that! I'll have update this PR with a corrected SVG later this evening.

**Comment by xrn** [comment]
@ryanml any progress here?

**Comment by ryanml** [comment]
going to go ahead and close this one as stale

**Pull request closed without merging**
