### PR TITLE
Add Polkamon

### PR DESCRIPTION
**Pull request by fnnhnsn**
Hi guys,

We would like to add Polkamon to MetaMask. You can find additional information below:

Website: [http://polkamon.com/](http://polkamon.com/) 
Etherscan: [https://etherscan.io/token/0x1796ae0b0fa4862485106a0de9b654efe301d0b2](https://etherscan.io/token/0x1796ae0b0fa4862485106a0de9b654efe301d0b2)
CoinGecko: [https://www.coingecko.com/en/coins/polkamon](https://www.coingecko.com/en/coins/polkamon)
CoinMarketCap: [https://coinmarketcap.com/currencies/polkamon/](https://coinmarketcap.com/currencies/polkamon/) 
GitHub: [https://github.com/polkamon/](https://github.com/polkamon/)
Twitter: [https://twitter.com/Polkamonorg](https://twitter.com/Polkamonorg)
OpenSea: [https://opensea.io/assets/polkamon](https://opensea.io/assets/polkamon)
Medium: [https://medium.com/polkamon](https://medium.com/polkamon)

**About us**

Polkamon are beautifully animated digital collectibles with varying scarcities. Each Polkamon is backed by a truly unique NFT and can be unpacked with $PMON tokens.

### CODE REVIEW

**Comment by xrn** [comment]
Hi @fnnhnsn can you please use address in EIP-55 format?

**Comment by fnnhnsn** [comment]
Hi @xrn thanks a lot for that fast reply, really appreciate it! Sure, just pushed an update, I hope it's fine like that. Feel free to reply anytime if there's still something missing or not fine.

**Comment by fakenine** [comment]
Finally, Polkamon logo on Metamask! :raised_hands:

**Comment by nakaryrzz** [comment]
Please add PMON to metamask

**Pull request merged**
