### PR TITLE
add usdd logo to metamask

### PR DESCRIPTION
**Pull request by zcloud42**
Add USDD logo support for ERC20 USDD token.

USDD website: https://usdd.io/ 

USDD address on Ethereum: 0x0C10bF8FcB7Bf5412187A595ab97a3609160b5c6

### CODE REVIEW

**Comment by html5-cloud** [comment]
When is the pull request expected to be merged

**Comment by zcloud42** [comment]
Why Nobody Merged PR Codes

**Review by MRabenda — APPROVED** [review]

**Comment by zcloud42** [comment]
thanks, I still can't see the usdd logo in metamask, fail loading

**Comment by MRabenda** [comment]
Hey,

It will require new release of this repo which will happen soon

**Pull request merged**
