### PR TITLE
Adding BZR token info and logo to Metamask

### PR DESCRIPTION
**Pull request by bazaars-project**
Bazaars website:
 https://bazaars.io/

BZR token contract address 
0x8d96B4ab6C741a4C8679AE323a100d74f085BA8F

Token tracker Etherscan :
https://etherscan.io/token/0x8d96b4ab6c741a4c8679ae323a100d74f085ba8f

Coingecko:
 https://www.coingecko.com/en/coins/bazaars

Whitepaper:
 https://bazaars.io/wp-content/uploads/2022/06/Bazaars.io-Whitepaper-v2.pdf

Security Audit:
 https://bazaars.io/wp-content/uploads/2022/06/audit.pdf

### CODE REVIEW

**Comment by MRabenda** [comment]
SVG image is required - can you please replace PNG one?

**Comment by bazaars-project** [comment]
BZR

**Comment by bazaars-project** [comment]
> SVG image is required - can you please replace PNG one?

Also updated the contract-map.json

Thank you

**Comment by MRabenda** [comment]
@bazaars-project - SVG image should be vectorized, sharp and regular should be ~ 5kB. Could you improve your icon especially since you have so a nice one :)?

**Comment by bazaars-project** [comment]
BZR

**Review by MRabenda — APPROVED** [review]

**Comment by bazaars-project** [comment]
Do we need to do anything else ?

**Comment by MRabenda** [comment]
For some reason tests are failing for your PR @bazaars-project can you run npm tests on your branch an make sure that everything is fine?

**Review by MRabenda — APPROVED** [review]

**Comment by bazaars-project** [comment]
Is it fine now?

**Comment by bazaars-project** [comment]
I got this error on npm test

Test (14.x)Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, actions/checkoutShow less
--
Test (16.x)Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, actions/checkout

**Comment by MRabenda** [comment]
@bazaars-project you have to move image from main folder to images is why tests are failing

**Comment by bazaars-project** [comment]
> @bazaars-project you have to move image from main folder to images is why tests are failing

Done, thank you

**Comment by bazaars-project** [comment]
Could we merge please

**Comment by bazaars-project** [comment]
Untitled-2

**Pull request merged**
