### PR TITLE
Add Camp

### PR DESCRIPTION
**Pull request by JoshepJang**
I want to show you the symbolic image erc-20 token in the metamask.

### CODE REVIEW

**Comment by xrn** [comment]
@JoshepJang 

1. Can you use contract address in EIP-55 version, please?
2. There is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

**Comment by xrn** [comment]
@JoshepJang 

1. Why you created issue #675?
2. Can you please update in the JSON address to EIP-55
3. Can you remove PNG file from pull request?

**Comment by JoshepJang** [comment]
Yes, sir. Thank you.

I modified it.

**Comment by xrn** [comment]
@JoshepJang thank you so much - it looks perfect, awesome job!

**Review by xrn — APPROVED** [review]

**Comment by JoshepJang** [comment]
> @JoshepJang thank you so much - it looks perfect, awesome job!

When will the camp image be updated?

**Pull request merged**
