### PR TITLE
QRX Logo Added

### PR DESCRIPTION
**Pull request by dharmveersinh**
Website: https://quiverx.io/
Whitepaper: https://quiverx-images.s3.amazonaws.com/QuiverXWhitepaper.pdf
CoinMarketCap: https://coinmarketcap.com/currencies/quiverx/
CoinGecko: https://www.coingecko.com/en/coins/quiverx/
UniSwap: https://info.uniswap.org/token/0x6e0dade58d2d89ebbe7afc384e3e4f15b70b14d8/
Telegram: https://t.me/joinchat/SJfRpBxjLExVcFYGwfMZSw
Github: https://github.com/QuiverX
Medium: https://quiverx.medium.com/
Etherscan: https://etherscan.io/address/0x6e0dade58d2d89ebbe7afc384e3e4f15b70b14d8

### CODE REVIEW

**Comment by dharmveersinh** [comment]
I am not able to figure out what's wrong with the test. Can anyone help me out?

**Comment by xrn** [comment]
Hi @dharmveersinh - please use the address in the EIP-55 version.

**Comment by dharmveersinh** [comment]
Hello @xrn, when should we expect the PR merge?

**Comment by dharmveersinh** [comment]
hello @xrn, just a follow-up when can we expect the merge.

**Comment by dharmveersinh** [comment]
Hello @xrn, when should we expect the PR merge?

**Comment by dharmveersinh** [comment]
Hello @xrn,
Now we have 1271 holders and 16176 and this numbers are constantly increasing. Can we have a PR merge now?

**Review by xrn — APPROVED** [review]

**Pull request merged**
