### PR TITLE
Add Yetucoin (YETU) token and logo

### PR DESCRIPTION
**Pull request by Mussassa**
Official website: https://yetubit.com/
White-paper: https://yetubit.com/files/yetubit_whitepaper.pdf
Token contract: https://bscscan.com/token/0x6652048fa5e66ed63a0225ffd7c82e106b0aa18b
CryptoCompare: https://www.cryptocompare.com/coins/yetu/overview
Twitter: https://twitter.com/yetuswap
Medium: https://medium.com/yetuswap
Youtube: https://www.youtube.com/channel/UChCNuNtoKsjNPH8uE6vuMRg
Facebook: https://www.facebook.com/yetuswap/
Telegram English: https://t.me/joinchat/D4XAg1e75T8FVYsf
Telegram Portuguese: https://t.me/joinchat/HWTuAoo8IadmsOHX

Please, let us know if you need any additional infromation.

Best regards,

Euclides Manuel.
Yetubit Founder.

### CODE REVIEW

**Comment by Mussassa** [comment]
Hello, 

Can you please check the changes that I made on the file? And if there's some mistake please let me know here on the comments

**Comment by xrn** [comment]
Hi @Mussassa 

1. Can you use an address in version EIP-55
2. Is there any chance that you will upload logo in SVG format smaller than 100Kb?

**Comment by Mussassa** [comment]
> Hi @Mussassa
> 
> 1. Can you use an address in version EIP-55
> 2. Is there any chance that you will upload logo in SVG format smaller than 100Kb?

Hello @xrn, thank you for answer me. 

1. I already putted a new address with EIP-55 version. 

2. I tried to compress the svg file for less than 100Kb but it's taking all the quality of the picture, I believe that it's better to use the one that I posted or a png file if it's possible.

Waiting for your reply,

Best regards,

Euclides Manuel.

**Comment by Mussassa** [comment]
And it's already green on the **ci/circleci: test-unit**!

**Comment by Mussassa** [comment]
Hello MR. @xrn 

I'm still waiting for your answer

**Comment by xrn** [comment]
@Mussassa this repository is used to store details about Ethereum assets, not Binance. Please provide information about Ethereum network smart contracts

**Comment by Mussassa** [comment]
I understand @xrn. Where can I add the tokens based on Binance Smart Chain on Metamask?

**Pull request closed without merging**
