### PR TITLE
Adding Pantos Token

### PR DESCRIPTION
**Pull request by jacekv**
Adding the Pantos Token with address and logo

### CODE REVIEW

**Comment by MRabenda** [comment]
1. EIP-55 address format is required
2. I would advice to have transparent background in SVG, it would be better handled in darkmode but it is optional

**Comment by jacekv** [comment]
Git it. Let me fix that :)

**Review by MRabenda — APPROVED** [review]

**Comment by jacekv** [comment]
What do we do in the case of an overlapping symbol? Seems like there is another entry which has the same symbol as we do @MRabenda ?

**Comment by MRabenda** [comment]
@jacekv After internal discussion - I removed that test, Can you rebase your PR with master? Then I should be able to merge it

**Comment by jacekv** [comment]
Done :) I hope that it passes this time @MRabenda

**Review by MRabenda — APPROVED** [review]

**Comment by MRabenda** [comment]
Thanks @jacekv

**Pull request merged**
