### PR TITLE
Add PUNKS comics

### PR DESCRIPTION
**Pull request by brennanfife**
Website: https://punkscomic.com/
Etherscan: https://etherscan.io/token/0x5ab21Ec0bfa0B29545230395e3Adaca7d552C948
Twitter: https://twitter.com/punkscomic?lang=en

### CODE REVIEW

**Comment by xrn** [comment]
Hi @brennanfife - thanks for your contribution - your SVG logo has ~ 250kb - the regular logo should be around 1kB, is there any chance that you will upload a smaller one?

**Comment by brennanfife** [comment]
@xrn Can we try this?

**Comment by xrn** [comment]
Hi @brennanfife - the current icon looks much better but something Is wrong with PR - in changes I should see only new token together with icon and at this moment there is 25 files

**Comment by brennanfife** [comment]
Not sure why the rebase caused this... Regardless, created a fresh PR: https://github.com/MetaMask/contract-metadata/pull/898

**Pull request closed without merging**
