### PR TITLE
Adding Kibble Token Info

### PR DESCRIPTION
**Pull request by InnoOkeke**
Relevant Links
Official Websites:
https://www.shibusociety.com/

Github: https://github.com/ShibuSocietyNFT
Twitter: https://twitter.com/shibusocietynft
Discord: http://discord.gg/deh3BdXQEZ

Etherscan token page: https://etherscan.io/token/0x65514b352d1d4a17DE97f95C7faB177C625Bd6ff

### CODE REVIEW

**Comment by InnoOkeke** [comment]
Relevant Links
Official Websites:
https://www.shibusociety.com/

Github: https://github.com/ShibuSocietyNFT
Twitter: https://twitter.com/shibusocietynft
Discord: http://discord.gg/deh3BdXQEZ

Etherscan token page: https://etherscan.io/token/0x65514b352d1d4a17DE97f95C7faB177C625Bd6ff

**Comment by InnoOkeke** [comment]
Hello @MRabenda,

Is there anything else required from us?

**Comment by MRabenda** [comment]
Regarding PR all looks fine, token just need a bit more holders and transfers

**Comment by ShibuSocietyNFT** [comment]
Hi @MRabenda 
We have now fulfilled the requirement of having more holders & transactions. Our token now has 174 holders & 183 teansactions. This amount will surely increase as more investors start staking their NFT( cause holders receive $Kibble tokens for staking their NFT)
Now that we have almost 200 holders can  our Token Logo now finally appear on Matamask??

Regards,
Team ShibuSociety

**Comment by InnoOkeke** [comment]
Hello @MRabenda,

The token holders and transfers has been updated. Please review and let us know the next step. 

Thank you.

**Pull request closed without merging**
