### PR TITLE
OTTERSPACE Add logo

### PR DESCRIPTION
**Pull request by EssEmmAych**
Token related links:
Basescan: https://basescan.org/token/0x7d95009cc9b47548203362b98347090f70f8c7c2
Website: https://www.otterspaceonbase.com/
Twitter: https://twitter.com/OtterSpaceBase
CoinMarketCap: https://coinmarketcap.com/currencies/otter-space/

### CODE REVIEW

**Comment by EssEmmAych** [comment]
Checking if contract-metadata provides support for Base Mainnet. If not, let me know and I'll close the PR.

**Comment by MRabenda** [comment]
Sorry but only Ethereum is supported at the moment

**Review by Mortiemi — COMMENTED** [review]
./scripts/ci/c-docs

**Review by Mortiemi — COMMENTED** [review]
Thank you so mutch

**Pull request closed without merging**
