### PR TITLE
Add ZKT token

### PR DESCRIPTION
**Pull request by mars-2008**

### CODE REVIEW

**Comment by mars-2008** [comment]
zkTube is a project built and developed on Layer 2 based on PLONK algorithm protocol using ZK-Rollup technology.
websites：https://zktube.io
repositories: https://github.com/zkTube-Labs
token: https://etherscan.io/token/0x07c52c2537D84e532a9F15d32E152C8B94D2b232

**Comment by xrn** [comment]
Please can you use SVG image?

**Comment by mars-2008** [comment]
> Please can you use SVG image?

yes

**Comment by mars-2008** [comment]
When did you merge the code into the main branch?

**Review by MRabenda — APPROVED** [review]

**Pull request merged**
