### PR TITLE
Oiler Token added

### PR DESCRIPTION
**Pull request by vicnaum**
https://oiler.network/

### CODE REVIEW

**Comment by xrn** [comment]
Hi @vicnaum can you solve conflicts please?

**Comment by vicnaum** [comment]
> Hi @vicnaum can you solve conflicts please?

Done

**Comment by xrn** [comment]
@vicnaum can you solve please conflicts one more time - I see that traction is here and I would like to merge this PR

**Comment by vicnaum** [comment]
> @vicnaum can you solve please conflicts one more time - I see that traction is here and I would like to merge this PR

Resolved

**Review by xrn — APPROVED** [review]

**Pull request merged**
