### PR TITLE
Add aria20

### PR DESCRIPTION
**Pull request by gnarco**
**ARIA20**

Website: https://arianee.org/
Etherscan: https://etherscan.io/token/0xedf6568618a00c6f0908bf7758a16f76b6e04af9
CoinGecko: https://www.coingecko.com/en/coins/arianee

Twitter: https://twitter.com/ArianeeProject
Discord: https://discord.gg/tTER79v
Telegram: https://t.me/arianeeproject
Github: https://github.com/Arianee
Medium: https://medium.com/arianee

### CODE REVIEW

**Comment by gnarco** [comment]
What does mean pending community activity ? more holders ? more transfer ? 
When can I ping you ?

**Review by xrn — APPROVED** [review]

**Comment by xrn** [comment]
@gnarco seems that community activity is here - can you solve conflicts, please?

**Comment by gnarco** [comment]
Hi ! 

Awesome !

Just pushed update to fix conflict

**Comment by gnarco** [comment]
@xrn

**Pull request merged**
