### PR TITLE
Added 4 new tokens from ibbt.io

### PR DESCRIPTION
**Pull request by geopayme**
Four new tokens from the ibbt.io platform.

InterGalactic Credits (CREE)
iBBT Utility (iBBT)
GEO Rewards (GEO)
Greek Drachma (GRD)

### CODE REVIEW

**Comment by geopayme** [comment]
Why is the checksum fails on this address 0x76ACE4E080C49F04A6C12756C036D3627F6B1E69 ?

**Comment by geopayme** [comment]
PR:
website: https://ibbt.io,
Contracts details on etherscan: 

https://etherscan.io/token/0xafcCbdA168681038419908470e79E2353a798E1f
https://etherscan.io/token/0x04a289fe4ce5fa87a76f58d0214340fb5893a58c
https://etherscan.io/token/0x7F77a0cc3caCE8c58ccE9D153c070f312D1a1088
https://etherscan.io/token/0x73489CE024bF775498D6eEC5dC56688f66Db48e1

**Comment by xrn** [comment]
Inactive contracts

**Comment by geopayme** [comment]
> Inactive contracts

What do you mean inactive? where is you find the information that gave you that conclusion after so many months of waiting?  https://www.ibbt.exchange

**Comment by xrn** [comment]
The last transactions for each contract here are over 30 days

**Comment by geopayme** [comment]
So why is that an issue to you ro metamask?? our members choose to hold
their tokens so who creates trade policy policies for token owners and
holders? I see tokens on Metamask that are fraud do you vbet them so see if
they are legal or active! I found your answer disturbing that now metamask
developers decide who places tokens on Metamask! - Maybe it's time to fork
Metamask to a new service!

Please reconsider and do not censor participation it goes against all that
the crypto community stands for!

Geopay.me Inc.

*"don't need to know everything, I just need to know where to find it."**A.
Einstein.*
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender, therefore, does not accept
liability for any errors or omissions in the contents of this message which
may arise as a result of email transmission.

**Pull request closed without merging**
