### PR TITLE
Adding GAME Credits as ERC20

### PR DESCRIPTION
**Pull request by meatsquirk**
[www.gamecredits.org
](www.gamecredits.org
)
Telegram
[GAME Telegram Channel](https://t.me/gamecreditsglobal)

In February of 2014 GAME Credits (GAME) was one of the very first cryptocurrencies launched and was the first to be focused solely on games. It’s primary
focus was as a digital currency, used to revolutionize in-game purchases and
give game developers a monetization based on the fair-play rules that the
technology of blockchain affords. Now GAME and Nova Token have merged into a single ERC-20 token and product offering allowing games and champions to sell provably rare items, players to earn rewards, and all to participate in provably fair esports tournaments.

### CODE REVIEW

**Comment by xrn** [comment]
@meatsquirk can you please remove conflicts and remove also spaces from SVG file name?

**Review by meatsquirk — COMMENTED** [review]
Removed spaces

**Review by meatsquirk — COMMENTED** [review]
Made fixes

**Review by meatsquirk — COMMENTED** [review]
I made changes needed

**Comment by xrn** [comment]
@meatsquirk your Json is incorrect, the object is not closed and I do not see decimals property. Can you fix it, please?

**Comment by meatsquirk** [comment]
> @meatsquirk your Json is incorrect, the object is not closed and I do not see decimals property. Can you fix it, please?

sorry, new to github, should be good now.

**Comment by meatsquirk** [comment]
@xrn any update on this?

**Comment by xrn** [comment]
@meatsquirk can you solve conflicts and change the name from `GAMECredits` to `GAME Credits` following implemented name in the smart contract - https://etherscan.io/token/0x63f88A2298a5c4AEE3c216Aa6D926B184a4b2437#readContract 

Then I will merge this PR

**Comment by meatsquirk** [comment]
Ok, i made the change to GAME Credits @xrn

**Review by xrn — APPROVED** [review]

**Comment by meatsquirk** [comment]
When does this go live in metamask itself?

**Comment by meatsquirk** [comment]
@xrn when does this go live in metamask?

**Pull request merged**
