### PR TITLE
adding kibble token

### PR DESCRIPTION
**Pull request by InnoOkeke**
Relevant Links
Official Websites:
https://www.shibusociety.com/

Github: https://github.com/ShibuSocietyNFT
Twitter: https://twitter.com/shibusocietynft
Discord: http://discord.gg/deh3BdXQEZ

Etherscan token page: https://etherscan.io/token/0x65514b352d1d4a17DE97f95C7faB177C625Bd6ff

### CODE REVIEW

**Comment by MRabenda** [comment]
@InnoOkeke can you please add SVG image as well to this PR?

**Comment by InnoOkeke** [comment]
> 

I'll do so as soon as possible. thanks

**Comment by InnoOkeke** [comment]
@MRabenda SVG image added. thank you

**Review by MRabenda — APPROVED** [review]

**Comment by InnoOkeke** [comment]
Hi @MRabenda 

This hasn't been merged please.

**Pull request merged**
