### PR TITLE
Pull Request for adding Zoracles (ZORA) Logo

### PR DESCRIPTION
**Pull request by StrategicReserve**
Pull Request for adding Zoracles (ZORA) Logo. 

ZORA Token
https://etherscan.io/token/0xD8E3FB3b08eBA982F2754988d70D57eDc0055ae6

Website
https://zoracles.com

GitHub
https://github.com/zoracles

Medium
https://zoracles.medium.com/

FAQ
https://zoracles.com/faq.pdf

Links
https://zoracles.com/links.pdf

Twitter
https://twitter.com/z0racles

Discord
https://discord.gg/cwJtkga

Telegram (Official channel)
https://t.me/zoracles

Uniswap ZORA-ETH Pair
https://info.uniswap.org/pair/0x18112da8f2d6576926fcfb4d2c511fe9c6f8b2b5

CoinGecko
https://www.coingecko.com/en/coins/zoracles

A New Product Aims To Disrupt Free Credit Scores With Blockchain Technology
https://www.entrepreneur.com/article/362584

Thank you!

### CODE REVIEW

**Comment by xrn** [comment]
Hi @StrategicReserve - thanks for your contribution. Is there a chance that you will upload SVG image smaller than 1.5MB? Regular SVG file has ~ 1KB

**Comment by StrategicReserve** [comment]
> Hi @StrategicReserve - thanks for your contribution. Is there a chance that you will upload SVG image smaller than 1.5MB? Regular SVG file has ~ 1KB

**Comment by StrategicReserve** [comment]
> > Hi @StrategicReserve - thanks for your contribution. Is there a chance that you will upload SVG image smaller than 1.5MB? Regular SVG file has ~ 1KB

I was able to reduce the file to 350 KB. It's a tough logo for SVG format. If it needs to be smaller, I will have to remove most of the details. Let me know if this is small enough

**Comment by StrategicReserve** [comment]
> Hi @StrategicReserve - thanks for your contribution. Is there a chance that you will upload SVG image smaller than 1.5MB? Regular SVG file has ~ 1KB

Let me know If you want me to start a new pull request of this reduced size SVG will work

**Comment by xrn** [comment]
Hi @StrategicReserve - thanks for the update. I will merge this PR but in the future if you will have a smaller SVG logo for your project please update it - it will improve the user experience.

**Review by xrn — APPROVED** [review]

**Pull request merged**
