### PR TITLE
Add support for BAG token

### PR DESCRIPTION
**Pull request by Garchbold**

### CODE REVIEW

**Comment by MRabenda** [comment]
Hey, before We would be able to merge it - I would like to improve icon quality:

1. Your image currently has some significant padding - do you want to have it?
2. Regular SVG logo like yours should be <15kB - current one is over 150kB, would you be able to work on better SVG image?

**Comment by Garchbold** [comment]
@MRabenda thanks for the followup, we were able to get it down ~25kb, is that sufficient. This is the smallest we could get it while keeping the colors intact.

**Comment by Garchbold** [comment]
Hey @MRabenda just checking in again is there still an outstanding issue for this pr?

**Comment by MRabenda** [comment]
I would be able to merge it with proper vector image, not a PNG saved as SVG

**Comment by MRabenda** [comment]
If is a full vector that should be fine, please update it

**Comment by Garchbold** [comment]
Hey @MRabenda just updated, please let me know if that works, thank you

**Review by MRabenda — APPROVED** [review]

**Comment by MRabenda** [comment]
Hey,

Icon looks good - last missing element is that address should be in EIP-55 format - the correct one would look like 0x808688c820AB080A6Ff1019F03E5EC227D9b522B

**Comment by Garchbold** [comment]
Thanks for all the patience @MRabenda it should be ready now

**Review by MRabenda — APPROVED** [review]

**Comment by b4u5** [comment]
when could we expect this to be reflected in prod?

**Comment by sahar-fehri** [comment]
Hello @Garchbold 👋 
Could you check now if the contract on polygon `0x73b29199a8e4c146e893eb95f18dac41738a88c6` has the right icon?

**Pull request merged**
