### PR TITLE
Add LMY Token

### PR DESCRIPTION
**Pull request by LunchMoneyToken**
Please add the Lunch Money token to the list of available tokens in metamask.

Official Website: https://lunchmoney.io/

Verified Token Source Code:
https://etherscan.io/address/0x66fd97a78d8854fec445cd1c80a07896b0b4851f#code

Token Explorer:
https://etherscan.io/token/0x66fd97a78d8854fec445cd1c80a07896b0b4851f

Thank you!

### CODE REVIEW

**Comment by xrn** [comment]
Hi @LunchMoneyToken  - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

**Comment by LunchMoneyToken** [comment]
> Hi @LunchMoneyToken - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

Thank you. Replacing PNG for SVG now.

**Comment by LunchMoneyToken** [comment]
@xrn we have replaced PNG for SVG, please merge this request asap.

**Comment by xrn** [comment]
This is just PNG file embedded into SVG extension. I will merge it for now but please remember to update your logo when you will have the right SVG one.

**Review by xrn — APPROVED** [review]

**Pull request merged**
