### PR TITLE
Support static images for mobile

### PR DESCRIPTION
**Pull request by Cal-L**
### **Issue**
- Mobile does not support template literals on `require` out of the box. Extension doesn't have this issue since webpack does support this. That's not to say that it's impossible for mobile, however, this change is meant as a dependency for the token detection feature and we'd like to keep the scope to a minimum.

### **Changes**
- The proposed solution generates and exports a module containing all `require`s for each static token. In turn, the mobile app will import this file and reference those logos locally.

### CODE REVIEW

**Comment by Gudahtt** [comment]
>Mobile does not support string expressions on require out of the box.

Could you elaborate on what this means? I don't know what "string expressions on require" are, or how this generated file solves the problem.

**Comment by Cal-L** [comment]
> > Mobile does not support string expressions on require out of the box.
> 
> Could you elaborate on what this means? I don't know what "string expressions on require" are, or how this generated file solves the problem.

@Gudahtt I updated the description to the use the correct terminology template literals on `require`. In React Native, this doesn't work out of the box. More on this [here](https://reactnative.dev/docs/images#:~:text=In%20order%20for%20this%20to%20work%2C%20the%20image%20name%20in%20require%20has%20to%20be%20known%20statically). The generated file solves this by defining what to require up front, which removes alleviates the need for template literal requires.

**Comment by Gudahtt** [comment]
Nothing on that page indicates to me that string template literals aren't supported :thinking: Moreover, I don't think it's possible for them _not_ to "support string template literals", as string templates are a language construct and are evaluated to strings at runtime. React Native's API would just get a string. If you mean the JavaScript runtime or transpiler you're using doesn't support them, that's a solvable problem, and also avoidable. Nothing about this requires string templates.

Even if it did, this seems well outside the responsibility of this package. This package is just a static list of token metadata and images. It isn't supported to support being embedded in React Native or anything really. I don't think this is the best place for things like this, even if it is required.

**Comment by Cal-L** [comment]
@Gudahtt Agreed, moving this code over to mobile and closing PR. Thanks!

**Pull request closed without merging**
