### PR TITLE
add wisdom token

### PR DESCRIPTION
**Pull request by gkucmierz**

### CODE REVIEW

**Comment by xrn** [comment]
Hi @gkucmierz  - can you change the PNG logo in JSON to SVG one?

**Comment by gkucmierz** [comment]
> Hi @gkucmierz - can you change the PNG logo in JSON to SVG one?

Sure, done! Sorry I forgot.

**Review by xrn — APPROVED** [review]

**Comment by xrn** [comment]
@gkucmierz can you provide some links/details about the project?

**Comment by gkucmierz** [comment]
@xrn I am just developer in this project.

I belive he can tell you more stuff: https://github.com/przeor

Oficial web-page is: https://experty.io/

**Comment by xrn** [comment]
Rebranding and Token Upgrade Announcement: https://medium.com/@experty_io/the-experty-wisdom-token-wis-is-live-af621c475f3a

**Comment by gkucmierz** [comment]
> @gkucmierz can you provide some links/details about the project? If I am correct this is your old contract `0x5c743a35e903f6c584514ec617acee0611cf44f3` what about it? it is deprecated? Will be still in use? Any announcement about migration?

`0x5c743a35e903f6c584514ec617acee0611cf44f3` that is old contract - amounts were copied from it and deployed into new contract with 3 differences:
- changed address who was owned by kucoin hacker
- changed idex and etherdelta address in order to process transfers manually
- added not generated tokens in 1-st phase

**Pull request merged**
