### PR TITLE
Add PlotX (PLOT) to MetaMask

### PR DESCRIPTION
**Pull request by ankit5902**
**PlotX** is a non-custodial prediction market protocol that enables users to earn rewards on high-yield prediction markets. Dubbed as the Uniswap of Prediction Markets, PlotX uses an Automated Market Making algorithm to settle markets and distribute rewards on the Ethereum Blockchain without any counterparty risk. Markets are focused on crypto-pairs like BTC-USD & ETH-USD and created in intervals of 4h, 1d, and 1w.

**Media publications:**
1. https://www.coindesk.com/investors-india-defi-scene-central-bank-ban
2. https://cointelegraph.com/news/looks-like-defi-is-coming-to-prediction-markets
3. https://www.newsbtc.com/all/former-nexus-mutual-and-govblocks-developers-launch-uniswap-for-prediction-market/
4. https://blockonomi.com/plotx-guide/

 Website: https://plotx.io 
Etherscan: https://etherscan.io/token/0x72F020f8f3E8fd9382705723Cd26380f8D0c66Bb
Github: https://github.com/plotx
Twitter: https://twitter.com/TryPlotX 
Medium: https://medium.com/plotx
Facebook: https://www.facebook.com/TryPlotX
Discord: https://discord.com/invite/8CWNQnG
Reddit: https://www.reddit.com/r/PlotX/
Telegram: https://t.me/plotx_official
CoinGecko: https://www.coingecko.com/en/coins/plotx

### CODE REVIEW

**Comment by xrn** [comment]
Hi @ankit5902 - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

**Comment by ankit5902** [comment]
@xrn Sure. I’ll get it replaced.

**Comment by ankit5902** [comment]
@xrn I have updated the PlotX (PLOT) Logo in SVG format. Kindly check and let me know if there are any changes to be made.

**Comment by xrn** [comment]
@ankit5902 Thanks

Please check that logo - https://github.com/MetaMask/contract-metadata/blob/bd2154811eb75deb78e1407a064f624d366e9746/images/plotx.svg seems that something is wrong here I think

Also, you did not change extension of the logo in the JSON file

**Comment by ankit5902** [comment]
Ah! I see, let me get it corrected. Thanks, @xrn!

**Comment by ankit5902** [comment]
@xrn I have updated and corrected both the JSON and SVG files. Please check and let me know if still there are any issues.

**Review by xrn — APPROVED** [review]

**Comment by ankit5902** [comment]
@xrn It still isn't showing the Logo on MetaMask. Is there a time frame after which it gets updated or am I missing something?

**Comment by ankit5902** [comment]
Got it, I guess it'll be pushed with the next release.

**Comment by ankit5902** [comment]
@xrn I see that the new release has already been pushed but the logo is still isn't showing on MetaMask. Is there a time frame after which it gets updated or am I missing something?

**Comment by xrn** [comment]
@ankit5902 please update MM extension to newest version - everything should be ok

**Comment by ankit5902** [comment]
@xrn Already updated the MetaMask extension and the MetaMask App as well. But still, the logo isn't reflecting in either of them.

**Comment by xrn** [comment]
@ankit5902 can you send me your MM version please?

mm

**Pull request merged**
