### PR TITLE
Add unFederalReserve and UN tokens

### PR DESCRIPTION
**Pull request by b1ckchn**
Hi guys,

We would like to add unFederalReserve and our UN ERC-20 tokens to MetaMask.

Website: https://unfederalreserve.com/
Etherscan: https://etherscan.io/token/0x5218e472cfcfe0b64a064f055b43b4cdc9efd3a6
CoinGecko: https://www.coingecko.com/en/coins/unfederalreserve
GitHub: https://github.com/UnFederalReserve
Twitter: https://twitter.com/Unfederalreser1
Medium: https://unfederalreserve.medium.com/
ReserveLending: https://lending.unfederalreserve.com/
TokenList.org: https://tokenlists.org/token-list?url=https://raw.githubusercontent.com/UnFederalReserve/token-lists/main/unfederalreserve_tokenlist.json

Description
unFederalReserve is a banking SaaS company built on blockchain technology. Our banking products are designed for smaller U.S. Treasury chartered banks and non-bank lenders in need of greater liquidity without sacrificing security or compliance. 

Reserve Lending on the unFederalReserve platform is a fork of Compound. For everyday DeFi users, this means the Reserve Lending platform benefits from a long history of stable, secure transactions. As a B2B lending platform, unFederalReserve provides tools to businesses that do not have access to more traditional methods of borrowing.

### CODE REVIEW

**Review by xrn — APPROVED** [review]

**Review by xrn — CHANGES_REQUESTED** [review]
Please change addresses to EIP-55 version

**Review by b1ckchn — COMMENTED** [review]
Updated unFederalReserve addresses to EIP-55 version

**Comment by b1ckchn** [comment]
> Please change addresses to EIP-55 version

Updated unFederalReserve addresses to EIP-55 version.  Please review changes for submission.

**Review by xrn — APPROVED** [review]

**Review by xrn — CHANGES_REQUESTED** [review]
unDAI symbol is used twice - symbol should be unique

**Review by b1ckchn — COMMENTED** [review]
Updated unDAI to unUSDC

**Review by xrn — APPROVED** [review]

**Comment by b1ckchn** [comment]
@xrn I see the check failed but not seeing what tokens it mentioned it is overlapping 

```
# symbols should not overlap
ok 4904 symbols should not overlap

1..4904
# tests 4904
# pass  4903
# fail  1

Error: Process completed with exit code 1.
```

**Comment by b1ckchn** [comment]
@xrn let me know if there is anything on my end that is needed to get this to pass checks and get properly merged.  Thanks again for all the help here!

**Comment by xrn** [comment]
@b1ckchn can you please merge our master to your code and add to this PR - I made changes in tests which allows for symbols longer than 6 chars

**Comment by b1ckchn** [comment]
> @b1ckchn can you please merge our master to your code and add to this PR - I made changes in tests which allows for symbols longer than 6 chars

@xrn Thanks!  merged your master into local branch which updated code.  See if things look better now.

**Pull request merged**
