### PR TITLE
Add ZAP TOKEN

### PR DESCRIPTION
**Pull request by pynchmeister**
Contract Address: https://etherscan.io/address/0x6781a0f84c7e9e846dcb84a9a5bd49333067b104#code

CMC:https://coinmarketcap.com/currencies/zap/

CoinGecko: https://www.coingecko.com/en/coins/zap

Website: Zap.org
Twitter: @ZapProtocol
Discord: discord.gg/pvHzemX
Telegram: t.me/ZapOracles
Reddit: r/ZapProtocol
Facebook: @ZapProtocol
Instagram: @ZapProtocol
Medium: The Zap Project
LinkedIn: Zap
GitHub: The Zap Project

### CODE REVIEW

**Comment by xrn** [comment]
Hi @pynchmeister, thank you for your PR 

1. Can you resolve conflicts?
2. Can you update contract address to follow EIP-55 - this is right version 0x6781a0F84c7E9e846DCb84A9a5bd49333067b104
3. There is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one?

Thanks

**Comment by pynchmeister** [comment]
Done @xrn , let me know if there are any issues.

**Comment by xrn** [comment]
Hi @pynchmeister 

1. Can you update the logo name in JSON - there is still PNG
2. Your SVG image is very large over 300KB - can you share something smaller - it is not usual size for SVG icon. Maybe you can use a blue monochromatic version of the logo like - https://www.pickacrypto.com/wp-content/uploads/2019/03/ZAP-Review-Logo.jpg (just blue icon with zap)

**Comment by pynchmeister** [comment]
hello @xrn I have resolved all of the issues above. Let me know if there is anything else.

**Comment by xrn** [comment]
Hi, @pynchmeister - thanks for the update. Looks like you are missing decimals in your JSON.

**Comment by pynchmeister** [comment]
hey @xrn fixed.

**Review by xrn — APPROVED** [review]

**Comment by pynchmeister** [comment]
hey @xrn when will I see these change reflected? I am still seeing a standard image in the token menu

**Comment by pynchmeister** [comment]
@xrn

**Comment by xrn** [comment]
Hi @pynchmeister - ZAP token has to be included in the new release of this repository and then in the new release of MetaMask - it can take the next 2-3 weeks.

**Comment by pynchmeister** [comment]
Ok thanks for the information @xrn , I was very confused.

**Pull request merged**
