### PR TITLE
Add RSR and RSV tokens

### PR DESCRIPTION
**Pull request by tbrent**

### CODE REVIEW

**Comment by xrn** [comment]
Hi @tbrent can you solve conflicts please?

**Comment by tbrent** [comment]
> Hi @tbrent can you solve conflicts please?

Done!

**Comment by xrn** [comment]
@tbrent my apologies - I missed this. Can I ask you one more time to solve them now I will merge

**Comment by tbrent** [comment]
> @tbrent my apologies - I missed this. Can I ask you one more time to solve them now I will merge

Done!

**Review by xrn — APPROVED** [review]

**Pull request merged**
