### PR TITLE
Add Belifex (BEFX) token

### PR DESCRIPTION
**Pull request by Belifex**

### CODE REVIEW

**Comment by xrn** [comment]
Hi @Belifex 

`0xFFC97d72E13E01096502Cb8Eb52dEe56f74DAD7B` is not an address of Belifex Contract

**Review by Belifex — COMMENTED** [review]
Adjusted

**Comment by xrn** [comment]
@Belifex you did not change the contract of Belifex but Fantom

**Review by Belifex — COMMENTED** [review]
ok now its should be ok

**Comment by Belifex** [comment]
damn i guess i need more sleep

**Comment by Belifex** [comment]
What does this label mean?

**Comment by xrn** [comment]
@Belifex currently this smart contract has 2 holders and 3 transactions. We will be monitoring it and when community activity will grow we will add it to that repository.

**Comment by Belifex** [comment]
Well, it is currently the newly created contract for Belifex, we will start swapping soon since our main exchange has been hacked and resulted in a loss of 215M tokens.

**Comment by xrn** [comment]
Can you provide details of old one?

**Comment by Belifex** [comment]
yes sure, https://etherscan.io/token/0xb91c2a2b953d72f3ef890490669a0a41b0add5f7

**Comment by xrn** [comment]
Contract do not have transfers more that 100 days

**Pull request closed without merging**
