### PR TITLE
Shina Inu add logo and info

### PR DESCRIPTION
**Pull request by Sheikhinu**
Hi Metamask Team. This PR adds the Shina Inu Token icon. Thank you so much. 💕

Official Project Website: https://shinatoken.com
Please see our whitepaper for an explanation of the project.

We have a very actively engaged community across Twitter, Discord and Telegram.

We have verified source code on Etherscan and we are listed on the following websites:

CoinGecko: https://www.coingecko.com/en/coins/shina-inu CoinMarketCap: https://coinmarketcap.com/currencies/shina-inu/ Etherscan: https://etherscan.io/token/0x243cacb4d5ff6814ad668c3e225246efa886ad5a Thank you. 💕
Shina Token Team
https://shinatoken.com

### CODE REVIEW

**Comment by Sheikhinu** [comment]
@MRabenda

**Comment by Sheikhinu** [comment]
@MRabenda @MRabenda @MRabenda

**Comment by Sheikhinu** [comment]
@MRabenda @MRabenda

**Comment by Sheikhinu** [comment]
@mcmire 
hey 
can you check our PR?
THANKS!

**Comment by Sheikhinu** [comment]
@MRabenda 
hey
can you check our PR?
THANKS!

**Comment by Sheikhinu** [comment]
@MRabenda

**Comment by MRabenda** [comment]
https://github.com/MetaMask/contract-metadata/pull/1033 merged

**Pull request closed without merging**
