### PR TITLE
Axion Logo

### PR DESCRIPTION
**Pull request by Mvii7**
https://axion.network/

### CODE REVIEW

**Comment by Mvii7** [comment]
What's wrong?

**Comment by xrn** [comment]
@Mvii7 there can not be 2 tokens with the same symbol

**Comment by Mvii7** [comment]
> @Mvii7 there can not be 2 tokens with the same symbol

Thanks, fixed.

**Comment by xrn** [comment]
@Mvii7 can you please change the name of the SVG image from axion-old.svg to obsolate.svg (please remember to change it in JSON also. Thanks in advance

**Comment by Mvii7** [comment]
> @Mvii7 can you please change the name of the SVG image from axion-old.svg to obsolate.svg (please remember to change it in JSON also. Thanks in advance

Done

**Review by xrn — APPROVED** [review]

**Pull request merged**
