### PR TITLE
add ACH's token LOGO

### PR DESCRIPTION
**Pull request by thinkbankcoin**
In MetaMask, the token ACH cannot add tokens directly through search, nor directly display the ACH logo. Please approve my application. thank you very much!

### CODE REVIEW

**Comment by thinkbankcoin** [comment]
Does the code and content I submit meet the standards?
If the merge is successful, is it possible to add the ACH token by searching for ACH in MetaMask.

**Comment by thinkbankcoin** [comment]
Can it be merged? Please tell me, thank you!

**Comment by thinkbankcoin** [comment]
thinkbankcoin:master

**Comment by MRabenda** [comment]
1. Please use address in EIP-55 format
2. Regular SVG logo should be <5kB uploaded one have 200kB could you please upload smaller one?

**Comment by thinkbankcoin** [comment]
> 1. Please use address in EIP-55 format
> 2. Regular SVG logo should be <5kB uploaded one have 200kB could you please upload smaller one?

thank you for your reply!
Can you give me a reference case for EIP-55?
I'm trying to make a logo smaller than 5KB.

**Comment by thinkbankcoin** [comment]
> 1. Please use address in EIP-55 format
> 2. Regular SVG logo should be <5kB uploaded one have 200kB could you please upload smaller one?

The change of logo has been completed

**Review by MRabenda — APPROVED** [review]

**Pull request merged**
