### PR TITLE
Add SAND and LAND Token

### PR DESCRIPTION
**Pull request by brennanfife**
SAND
Token Address: 0x3845badAde8e6dFF049820680d1F14bD3903a5d0
Token Name: The Sandbox SAND Token
Token Decimals: 18
Token Symbol: SAND

LAND
Token Address: 0x50f5474724e0Ee42D9a4e711ccFB275809Fd6d4a
Token Name: The Sandbox LAND Token
Token Decimals: 0
Token Symbol: LAND

Etherscan (SAND): https://etherscan.io/token/0x3845badade8e6dff049820680d1f14bd3903a5d0
Etherscan (LAND): https://etherscan.io/token/0x50f5474724e0ee42d9a4e711ccfb275809fd6d4a
Coingecko: https://www.coingecko.com/en/coins/the-sandbox
Coinmarketcap: https://coinmarketcap.com/currencies/the-sandbox/

Project website: https://www.sandbox.game/en/
Twitter: https://twitter.com/TheSandboxGame
Telegram: https://t.me/sandboxgame
Github: https://github.com/thesandboxgame
Medium: https://medium.com/sandbox-game

### CODE REVIEW

**Comment by xrn** [comment]
Hi,

I would double check - for `0x3845badAde8e6dFF049820680d1F14bD3903a5d0` there should be sandbox in name field as well?

**Comment by brennanfife** [comment]
@xrn Sorry for the confusion. Are you suggesting the name property I have listed for SAND, "The Sandbox SAND Token", be changed to something else?

**Comment by xrn** [comment]
Correct 

For address - https://etherscan.io/token/0x50f5474724e0Ee42D9a4e711ccFB275809Fd6d4a - we have name interface in contract which returns `Sandbox's LANDs ` 

For address - https://etherscan.io/token/0x3845badAde8e6dFF049820680d1F14bD3903a5d0 - name interface returns SAND 

I would like to double-check if name in this PR should be SAND or The Sandbox SAND Token

**Comment by brennanfife** [comment]
@xrn Made the required changes

**Review by xrn — APPROVED** [review]

**Pull request merged**
