### PR TITLE
Add a logo for ACH to MetaMask

### PR DESCRIPTION
**Pull request by thinkbankcoin**
Add a logo for ACH to MetaMask so that users can add tokens directly through the symbol search.
AlchemyPay
ERC20:0xed04915c23f00a313a544955524eb7dbd823143d   
BSC:0xbc7d6b50616989655afd682fb42743507003056d

Contract browser:
https://cn.etherscan.com/token/0xed04915c23f00a313a544955524eb7dbd823143d#balances
https://explorer.binance.org/asset/0xbc7d6b50616989655afd682fb42743507003056d
The ACH token has completed the cross-chain of ERC20 and BEP20. ACH (ERC20) and ACH (BEP20) deposits and withdrawals are now directly available on Binance. ACH (ERC20) and ACH (BEP20) can be exchanged 1:1 on AnySwap.

introduce:
AlchemyPay is the pioneer of Hybrid Crypto-Fiat Gateway that is bridging the gap between the fiat and crypto economies - driving crypto adoption by making payments, blockchain solutions and DeFI services readily available to everyone.

AlchemyPay's token is ACH, and the contract has been audited. Here is a link to the audit report:
https://drive.google.com/file/d/1HTbnpve30kw9RdFEi3MZR44mwuq3dRSQ/view?usp=sharing

Official website and media:
https://www.alchemytech.io/index.html
https://twitter.com/AlchemyPay
https://github.com/Alchemy-GPS/ERC20Token/blob/master/ACH.sol
https://t.me/alchemy_official
https://t.me/Alchemy_Notice
https://www.youtube.com/c/AlchemyPay
https://coinmarketcap.com/zh/currencies/alchemy-pay/
https://www.reddit.com/r/AlchemyPay/
https://alchemygps.medium.com/

### CODE REVIEW

**Comment by MRabenda** [comment]
1. Please provide SVG image <5Kb

**Comment by thinkbankcoin** [comment]
we have fixed the conflict,Please review it again.Thanks!

**Comment by thinkbankcoin** [comment]
The test has been completed, please help to check.
Thank you for MateMask's team.

**Comment by thinkbankcoin** [comment]
> 1. Please provide SVG image <5Kb
We have fixed the conflict.
The test has been completed, please help to check.

**Comment by thinkbankcoin** [comment]
Can ACH merge now? What else is required for a merger?

**Comment by thinkbankcoin** [comment]
> This PR is empty
Has the ACH mark merger I applied for succeeded?
Now just have to wait for the new version to be released?
If so, please help me close this request.
thank you for your reply! ! !

**Comment by MRabenda** [comment]
The new release should be available in next 2 weeks

**Comment by thinkbankcoin** [comment]
Thank you very much !!!

**Pull request closed without merging**
