### PR TITLE
Update Hydro token address

### PR DESCRIPTION
**Pull request by ayushyahydro**
Project Hydro redeployed their contract, therefore it requires an update in the smart contract address. The redeployment completion announcement link is https://projecthydro.medium.com/hydro-smart-contract-redeployment-57bf0e1f3fb4

### CODE REVIEW

**Comment by xrn** [comment]
There is requirement that logo should be in SVG format.

**Comment by ayushyahydro** [comment]
Logo in SVG format has been added as a new file.

However, the filename hydro.png has been used in metamask mobile wallet. Updating name from hydro.png to hydro.svg might cause problems in mobile wallet.

**Comment by xrn** [comment]
It should not be problem at all - please remove png file and change file name in a json to svg

**Comment by ayushyahydro** [comment]
@xrn PNG file has been removed.

**Comment by xrn** [comment]
Address has to be EIP-55 format

**Comment by ayushyahydro** [comment]
@xrn The address has been updated.

**Comment by ayushyahydro** [comment]
Requesting approval from @davidwgrossman and @TheCollectiveDevs

**Pull request merged**
