### PR TITLE
Add ArkiTech to the contract-map.json

### PR DESCRIPTION
**Pull request by CraigArkiTechAi**
Add ArkiTech to the contract-map.json
Add logo to images folder (ARKI.SVG) 

Contract address: 0xd3210F246Ae54C5a45A7b4A83315bf718F591bfc

Website: https://arkitech.ai

### CODE REVIEW

**Comment by MRabenda** [comment]
Hey, svg image is required

**Comment by CraigArkiTechAi** [comment]
> Hey, svg image is required

will upload asap.

**Comment by CraigArkiTechAi** [comment]
> Hey, svg image is required

Please let me know if the quality is sufficient or not.

**Comment by MRabenda** [comment]
Please update .png to .svg in JSON and remove PNG image from PR

**Comment by CraigArkiTechAi** [comment]
> Please update .png to .svg in JSON and remove PNG image from PR

Complete

**Comment by MRabenda** [comment]
Last fast question - do you want to remove the padding from an icon on this is a correct representation of it? If sth I can help with that one

**Comment by CraigArkiTechAi** [comment]
> Last fast question - do you want to remove the padding from an icon on this is a correct representation of it? If sth I can help with that one

Yes if you could remove the padding I would appreciate it!

**Comment by MRabenda** [comment]
During edit I realized that this image has over 4Mb - which is a lot. We are looking for light SVG for our clients - logo like this should be < 10 kB would you be able to create proper SVG image of small size with few vector paths?

**Comment by CraigArkiTechAi** [comment]
> During edit I realized that this image has over 4Mb - which is a lot. We are looking for light SVG for our clients - logo like this should be < 10 kB would you be able to create proper SVG image of small size with few vector paths?

Uploaded

**Comment by CraigArkiTechAi** [comment]
Anything else needed?

**Comment by MRabenda** [comment]
Sorry @CraigArkiTechAi to say this but this image still does not satisfy requirements - what you posted in PNG encoded to SVG (inside a code we can find PNG file), which means this is not a vector version. I would still ask you to upload correct, small SVG as a vector version of the signet.

**Comment by CraigArkiTechAi** [comment]
> Sorry @CraigArkiTechAi to say this but this image still does not satisfy requirements - what you posted in PNG encoded to SVG (inside a code we can find PNG file), which means this is not a vector version. I would still ask you to upload correct, small SVG as a vector version of the signet.

not a problem i hired someone else, should be done tomorrow, thanks for your patience!

**Comment by CraigArkiTechAi** [comment]
> Sorry @CraigArkiTechAi to say this but this image still does not satisfy requirements - what you posted in PNG encoded to SVG (inside a code we can find PNG file), which means this is not a vector version. I would still ask you to upload correct, small SVG as a vector version of the signet.

Uploaded the new 4KB SVG, thanks!

**Review by MRabenda — APPROVED** [review]

**Comment by MRabenda** [comment]
Thanks for your contribution @CraigArkiTechAi

**Review by MRabenda — APPROVED** [review]

**Comment by CraigArkiTechAi** [comment]
It looks like the full logo isn't fitting on the wallet, do I need to get the artist to resize?

@MRabenda

**Comment by MRabenda** [comment]
@CraigArkiTechAi can you post a screenshot of the wallet - what is the problem?

**Comment by CraigArkiTechAi** [comment]
> @CraigArkiTechAi can you post a screenshot of the wallet - what is the problem?

FireShot Capture 016 - MetaMask Portfolio - Token Detail - portfolio metamask io

The full logo is not fitting in the circle, the bottom corners are chopped off.

This is the same inside the wallet, but inside the wallet it has a grey background instead of white.

**Comment by MRabenda** [comment]
Yes, wallet uses rounded icons together with network marks. If you would like to change how it would be displayed please update image

**Pull request merged**
