### PR TITLE
Add Shine

### PR DESCRIPTION
**Pull request by ShineDAO**
Hi guys,

We would like to add Shine (SHN) to MetaMask. You can find information below:

Website: http://shinedao.finance/
Etherscan: https://etherscan.io/token/0x1C7ede23b1361acC098A1e357C9085D131b34a01
Twitter: https://twitter.com/ShineDAO_
Medium: https://shine-squad.medium.com/

About us

ShineDAO is a community-run incubator where the interests of early stage projects and community members are aligned by providing various Incentives.

### CODE REVIEW

**Comment by ShineDAO** [comment]
@ryanml 

Just a bump if we can get approved. A small community is waiting for you to finally have our icon in metamask.

**Comment by ShineDAO** [comment]
Hello @xrn , is it possible to merge this PR? What is the meaning of the "pending community activity" label?

**Comment by xrn** [comment]
Hi @ShineDAO 

This token has ~ 100 holder and ~ 300 transactions - when do community activity will grow PR will be merged

**Comment by MRabenda** [comment]
Not active token

**Pull request closed without merging**
