### PR TITLE
Axion

### PR DESCRIPTION
**Pull request by Mvii7**
https://axion.network/

### CODE REVIEW

**Comment by xrn** [comment]
Hi @Mvii7  - There is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

**Comment by Mvii7** [comment]
What went wrong?

**Comment by xrn** [comment]
You did not change json icon name

**Comment by Mvii7** [comment]
Yeah just realised, should be fine now

**Review by xrn — APPROVED** [review]

**Pull request merged**
