### PR TITLE
Update TUSD LOGO

### PR DESCRIPTION
**Pull request by RandomGly**
Update TUSD LOGO

### CODE REVIEW

**Comment by xrn** [comment]
Hi @RandomGly - sth is wrong with this logo - can you fix/update, please? https://github.com/MetaMask/contract-metadata/blob/905324583cfb4154cc423a25b78d921589c0c2aa/images/tusd.svg

**Comment by xrn** [comment]
@RandomGly if you have access to updated logotypes - can you add all TrustToken products? https://www.trusttoken.com/products to this repo?

**Comment by RandomGly** [comment]
> @RandomGly if you have access to updated logotypes - can you add all TrustToken products? https://www.trusttoken.com/products to this repo?
https://trueusd.medium.com/scaling-trust-announcing-tusds-next-stage-of-growth-f1fb58d62b
https://www.trusttoken.com/  change  https://www.trueusd.com/

**Comment by RandomGly** [comment]
https://www.trueusd.com/ update TUSD LOGO

**Comment by xrn** [comment]
Hi @RandomGly - in this repo we require SVG images. Please change the uploaded PNG to SVG one

**Comment by RandomGly** [comment]
> Hi @RandomGly - in this repo we require SVG images. Please change the uploaded PNG to SVG one



> Hi @RandomGly - in this repo we require SVG images. Please change the uploaded PNG to SVG one

It's OK this time

**Review by xrn — APPROVED** [review]

**Comment by xrn** [comment]
You have to rename `TUSD.svg` to `tusd.svg` or update JSON

**Comment by RandomGly** [comment]
> You have to rename `TUSD.svg` to `tusd.svg` or update JSON

Ok Thank you!  Update completed

**Review by xrn — APPROVED** [review]

**Comment by RandomGly** [comment]
> > You have to rename `TUSD.svg` to `tusd.svg` or update JSON
> 
> Ok Thank you! Update completed
MetaMask Wallet's TUSD logo not update

**Comment by RandomGly** [comment]
MetaMask Wallet's TUSD logo not update

**Comment by xrn** [comment]
Hi @RandomGly you have to wait for the release in this repository and then release of new MM version - this can take 2-3 weeks from now.

**Comment by RandomGly** [comment]
> Hi @RandomGly you have to wait for the release in this repository and then release of new MM version - this can take 2-3 weeks from now.



> Hi @RandomGly you have to wait for the release in this repository and then release of new MM version - this can take 2-3 weeks from now.

Ok Thanks!

**Pull request merged**
