### PR TITLE
Add Rupiah Token (IDRT)

### PR DESCRIPTION
**Pull request by fengkiej**
Rupiah Token (IDRT) is the first Ethereum-based Token (ERC-20) that is fully collateralized 1:1 by Rupiah (IDR) fiat currency. Each IDRT is backed by equivalent amount of Fiat Rupiah, and can be redeemed for Fiat through our platform.

Project website: https://rupiahtoken.com
Etherscan: https://etherscan.io/token/0x998FFE1E43fAcffb941dc337dD0468d52bA5b48A
Medium: https://medium.com/rupiahtoken-blog
Telegram group: https://t.me/joinchat/IecbjxEy6xVf1dyZhGZxpw
Twitter: https://twitter.com/RupiahTokenIDRT

### CODE REVIEW

**Comment by xrn** [comment]
Hi @fengkiej - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

**Comment by fengkiej** [comment]
Hi @xrn, thanks for your follow up! Sure we'll update the logo to svg file format

**Comment by fengkiej** [comment]
@xrn hi i have updated the logo file to svg

**Comment by xrn** [comment]
@fengkiej thanks for the update. You missed to update the name of the logo in the Json - can you also solve conflicts, please?

**Comment by fengkiej** [comment]
> @fengkiej thanks for the update. You missed to update the name of the logo in the Json - can you also solve conflicts, please?

oh sure! thanks a lot! @xrn

**Review by xrn — APPROVED** [review]

**Comment by xrn** [comment]
@fengkiej after 1 year but we did it :confetti_ball:

**Pull request merged**
