### PR TITLE
Add TOKAMAK NETWORK token

### PR DESCRIPTION
**Pull request by mandoopapa**
**Description**
Tokamak Network is a layer 2 protocol including plasma and roll-up that boosts interoperability, scalability, functionality, and usability, while the security and data availability are guaranteed by the decentralized Ethereum blockchain. Anyone can open an on-demand layer 2 solution and adapt it o their specific needs for scalability. The mission of Tokamak Network is to support various services from DApp projects to Ethereum infrastructure solutions, in order to meet the requirements for Ethereum mass adoption.

_**Tokamak Network Token**_
Network : Ethereum
Token Address : **`0x2be5e8c109e2197D077D13A82dAead6a9b3433C5`**
Symbol : TON
Etherscan(verified) : https://etherscan.io/token/0x2be5e8c109e2197D077D13A82dAead6a9b3433C5

_**Wrapped TON**_
Network : Ethereum
Token Address : **`0xc4A11aaf6ea915Ed7Ac194161d2fC9384F15bff2`**
Symbol : WTON
Etherscan(verified) : https://etherscan.io/token/0xc4a11aaf6ea915ed7ac194161d2fc9384f15bff2

Information about TON and WTON can also be found in CMC and Gecko. 
CoinMarketCap : https://coinmarketcap.com/currencies/tokamak-network/
CoinGecko : https://www.coingecko.com/en/coins/tokamak-network

**Official Website and Socials**
**Website** : https://www.tokamak.network/
**Twitter** : https://x.com/Tokamak_Network
**Telegram Channel** : https://t.me/tokamak_network

### CODE REVIEW

**Review by MRabenda — APPROVED** [review]

**Comment by MRabenda** [comment]
@mandoopapa thank you for your well prepared contribution

**Comment by suahnkim** [comment]
@mandoopapa @MRabenda 
Appreciate for merging the commit quickly! I want to ask questions regarding expected behavior since this has been merged.

Any insights on 
- Why Tokamak Network (TON) and Wrapped TON (WTON) cannot be searched on Metamask's search function? 
- Desktop Metamask, If the TON + WTON are added using custom import, the token logos do not show.  
- Mobile Metamask, if the TON + WTON are added using custom import, TON is working correctly, but WTON is showing the wrong logo (showing TON logo)

**Comment by MRabenda** [comment]
Hey @suahnkim - would you mind to check that thread https://github.com/MetaMask/contract-metadata/issues/1333 ? If you would have still follow up questions feel free to rise them here

**Comment by suahnkim** [comment]
hey @MRabenda I have 
1. Autodetect tokens enabled 
2. using Desktop chrome metamask version 11.16.16

- Still not showing up on Metamask's search function 
- Custom import still missing the logo for desktop 
- Mobile version's search does not work for TON and WTON (and logo is incorrect for WTON)

**Comment by suahnkim** [comment]
@MRabenda any updates or follow up would be appreciated~ thanks

**Comment by sahar-fehri** [comment]
Hello @suahnkim !
I am able to see the Tokamak Network Token on extension with token detection ON and mobile using search. Could you please check again to confirm?
Screenshot 2024-08-27 at 10 49 13

The Wrapped TON was not on enough of our token lists; could you please add Wrapped TON to Coingecko token [list](https://tokens.coingecko.com/ethereum/all.json)? It should be able to work with search function after that 🙏

**Comment by suahnkim** [comment]
Thanks for the clarification. 

Yes, I can see TON in both desktop and mobile. Thank you for your help.

**Pull request merged**
