### PR TITLE
Update contract-map.json

### PR DESCRIPTION
**Pull request by blurr2**
Added logo to MRF2.0

### CODE REVIEW

**Comment by blurr2** [comment]
please review so i can launch my token

**Comment by MRabenda** [comment]
Hey @blurr2,

1. Your JSON is incorrect -`{` has to be in first line of entire JSON
2. Use SVG image

**Comment by blurr2** [comment]
🫡

**Comment by MRabenda** [comment]
1. Did you saw preview of your logo? https://github.com/MetaMask/contract-metadata/blob/4f5a5d2659cde5e1713e563b8231f7b4cb8f1ab3/images/mrf.svg Is this correct one?
2. Do you have any project website? Twitter account, anything?

**Comment by blurr2** [comment]
yeah bro i know its a bit funky https://twitter.com/mrf2_0/status/1675809109332078593?s=46&t=VWX51pJQu__EDC2jL4c0bA

this is our twitter

**Pull request closed without merging**
