### PR TITLE
Add LAMB icon and info

### PR DESCRIPTION
**Pull request by steveliupai**
Relevant Links
[Official Websites](https://lambda.im/)

[Official Github](https://github.com/LambdaIM)
[Twitter](https://twitter.com/Lambdaim)
[Discord](https://t.co/kSnw2HC560)
[Coingecko](https://www.coingecko.com/en/coins/lambda)
[Etherscan verified token](https://etherscan.io/token/0x8971f9fd7196e5cee2c1032b50f656855af7dd26)

### CODE REVIEW

**Review by MRabenda — APPROVED** [review]

**Comment by MRabenda** [comment]
Hey @steveliupai - can you update the address to EIP-55 format?

**Comment by steveliupai** [comment]
> Hey @steveliupai - can you update the address to EIP-55 format?

Got it, will fix it asap

**Comment by steveliupai** [comment]
> Hey @steveliupai - can you update the address to EIP-55 format?

Fixed, thank you for the info!

**Comment by Sheikhinu** [comment]
@MRabenda can u check our PR sir ?

**Pull request merged**
