### PR TITLE
Add Monerium EUR, USD, GBP and ISK

### PR DESCRIPTION
**Pull request by arnigudj**
Monerium is an official partner of Consensys. 

The e-money tokens (EUR, GBP, USD and ISK) by Monerium EMI, a regulated entity, licensed in the EEA and the UK. 

E-money is recognised as a digital alternative to cash, 1:1 backed in high-quality liquid assets and is unconditionally redeemable on demand.

Monerium EMI helps you move euros between bank accounts worldwide and your blockchain wallet by creating a unique bank account number for the wallet in your name.

**Link to official project website**: [https://github.com/monerium/smart-contracts](https://github.com/monerium/smart-contracts)
**Project website that include explanation of project**: [https://monerium.com](https://monerium.com/)
**Etherscan**: [EUR](https://etherscan.io/token/0x3231cb76718cdef2155fc47b5286d82e6eda273f) [GBP](https://etherscan.io/token/0x7ba92741bf2a568abc6f1d3413c58c6e0244f8fd) [USD](https://etherscan.io/token/0xbc5142e0cc5eb16b47c63b0f033d4c2480853a52) [ISK](https://etherscan.io/token/0xc642549743a93674cf38d6431f75d6443f88e3e2)
**Social media**: [Linkedin](https://www.linkedin.com/company/monerium/) [Twitter](https://twitter.com/monerium) [Youtube](https://www.youtube.com/channel/UCGpDVQYER-saJ5bOH-ykZSQ)

### CODE REVIEW

**Comment by xrn** [comment]
Hi @arnigudj 

First of all thanks for your contribution. May I ask you for:

1. Changing the name for all contracts from `EUR | Monerium` to `Monerium EUR` following smart contract name
2. Solving conflicts in this PR

Thanks in advance

**Comment by arnigudj** [comment]
> Hi @arnigudj
> 
> First of all thanks for your contribution. May I ask you for:
> 
> 1. Changing the name for all contracts from `EUR | Monerium` to `Monerium EUR` following smart contract name
> 2. Solving conflicts in this PR
> 
> Thanks in advance

Hi @xrn, thank you for responding. Sure I can do these changes. 

For 1), can we please keep it as `EUR | Monerium`? If there are strong feeling about this, then we can change it to `Monerium EUR`. The reason why is because we want to emphasise that this is the actual euro, not a stablecoin euro.

**Comment by xrn** [comment]
Hi @arnigudj 

There is a lot of different tokens in the network and we are trying to keep the name as similar as possible with one used during contract deployment. I would like to advise you to change names to `Monerium EUR` like - I hope you will understand. Thanks in advance.

**Comment by arnigudj** [comment]
@xrn sure makes sense, thank you for taking the time to respond :) 
I've changed the names according to your suggestions. 

I hope this is ok now?

**Review by xrn — APPROVED** [review]

**Pull request merged**
