### PR TITLE
Add Dracula (DRC) token

### PR DESCRIPTION
**Pull request by aaronovz1**
Dracula Protocol is a universal DeFi adapter that aggregates interest earning strategies, known as yield farming, into a singular protocol. Dracula Protocol aims to consolidate various aspects of DeFi into one platform and is managed through a Distributed Autonomous Organization (DAO), in which voting rights are quantified by $DRC ownership.

Site: https://dracula.finance
Etherscan (DRC): https://etherscan.io/address/0xb78b3320493a4efaa1028130c5ba26f0b6085ef8
Github: https://github.com/Dracula-Protocol/contracts-v2
Blog: https://medium.com/@DraculaProtocol
Twitter: https://twitter.com/DraculaProtocol
Discord: https://discord.gg/7JgByFU
Coingecko: https://www.coingecko.com/en/coins/dracula-token

### CODE REVIEW

**Review by dutchcoin — APPROVED** [review]

**Review by kyjames — APPROVED** [review]

**Review by d34dh34dd — APPROVED** [review]

**Comment by xrn** [comment]
Hi @aaronovz1  - There is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

**Comment by aaronovz1** [comment]
Updated to SVG. Thanks!

**Comment by xrn** [comment]
@aaronovz1 thanks for the update. 

1. Your logo looks awesome but is a simple image - 65Kb is a lot, is there a chance that you will reduce it? A regular logo would be no bigger than 5Kb
2. Can you solve conflicts please?

**Comment by aaronovz1** [comment]
Thanks @xrn File size and conflict should be resolved now :+1:

**Pull request merged**
