### PR TITLE
Add OctoFi

### PR DESCRIPTION
**Pull request by octofi**
Thanks for everything you do for the space with MetaMask!

### OctoFi

- [Official project website](https://octo.fi)
- [Verified Etherscan token page](https://etherscan.io/token/0x7240aC91f01233BaAf8b064248E80feaA5912BA3)

### CODE REVIEW

**Comment by xrn** [comment]
Hi @octofi - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

**Comment by octofi** [comment]
Hey @xrn thanks for the feedback, we changed everything.

**Comment by xrn** [comment]
@octofi can you remove the PNG file from this PR and resolve conflicts, please?

**Comment by octofi** [comment]
Sorry @xrn for the inconvenience. Now everything is updated and checks passed. Thanks for having you and not giving up.

**Review by xrn — APPROVED** [review]

**Pull request merged**
