### PR TITLE
Add Insula Token (ISLA)

### PR DESCRIPTION
**Pull request by Calum-Insula**
Link to Insula website: https://insulainvestments.com
ISLA on Etherscan: https://etherscan.io/token/0x697ef32b4a3f5a4c39de1cb7563f24ca7bfc5947

### CODE REVIEW

**Comment by xrn** [comment]
Hi @Calum-Insula  - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Use also a different name for image file - Thanks

**Comment by Calum-Insula** [comment]
Hi @xrn I have made the changes that you requested, if you need anything else before you can merge please let me know.

**Comment by xrn** [comment]
@Calum-Insula thanks - but the name of the file in JSON is incorrect, please change it if possible

**Comment by Calum-Insula** [comment]
@xrn apologies, file name should be consistent now.

**Comment by Calum-Insula** [comment]
@xrn is there anything else we need to provide you with to proceed? I noted we were labelled with 'pending community activity.' We have over 500 token holders, nearly 10000 on chain transactions, a Telegram group with over 450 members and thousands of monthly unique visitors to our website. I'm happy to provide sources for this data if necessary.

**Review by xrn — APPROVED** [review]

**Review by xrn — APPROVED** [review]

**Pull request merged**
