### PR TITLE
add grody 

### PR DESCRIPTION
**Pull request by yakusag**

### CODE REVIEW

**Comment by xrn** [comment]
0x23F24E81994764ba838c0B1d53993d3c79A6fDFD <- on what chain this contract is deployed?

**Comment by yakusag** [comment]
On xDai

Le lun. 10 janv. 2022 à 16:10, Marcin Rabenda ***@***.***> a
écrit :

**Comment by yakusag** [comment]
What about logo

**Comment by xrn** [comment]
You have 2 svg files - can you remove 1?

**Pull request closed without merging**
