### PR TITLE
Add MMRL Loyalty Token

### PR DESCRIPTION
**Pull request by EITMJ**

### CODE REVIEW

**Comment by EITMJ** [comment]
Hi,
When we can expect merge?
Regards

**Review by EITMJ — COMMENTED** [review]
We are waiting for Merge

**Comment by MRabenda** [comment]
Address not active

**Comment by EITMJ** [comment]
Dear sir, We are still waiting for adding our MMRL Logo !Best regards,Marius Jedlickij Mob/ WhatsApp +971 508828056 Sent from my iPhoneOn 13 Sep 2023, at 13:37, MRabenda ***@***.***> wrote:﻿
Closed #1165.

**Comment by EITMJ** [comment]
Hi,Kindly add our MMRL logo & address will come active. Regards,Marius Jedlickij Mob/WhatsApp +971508828056Elite Icon Group ***@***.***) • Instagram photos and videosinstagram.comSent from my iPhoneOn 13 Sep 2023, at 13:37, MRabenda ***@***.***> wrote:﻿
Address not active

**Pull request closed without merging**
