### PR TITLE
Add USDN stablecoin

### PR DESCRIPTION
**Pull request by vlzhr**

### CODE REVIEW

**Comment by vlzhr** [comment]
https://neutrino.at

**Comment by vlzhr** [comment]
Some additional links:

ERC-20 USDN on Curve: https://www.curve.fi/usdn
ERC-20 USDN on Uniswap: https://info.uniswap.org/pair/0x73fb253681c2a2f11c9d5c8e731be44a3f46b353
ERC-20 USDN on Mooniswap: https://mooniswap.info/pair/0x10e67cf3265401a6366d484d2c1cb7fead21fae5

Media publications verifying that the token address is authentic:
https://medium.com/neutrinoteam/neutrino-ports-into-ethereum-26d9d5750669
https://medium.com/wavesprotocol/waves-issues-erc-20-for-collaboration-with-ethereum-network-122a968e6a09
https://twitter.com/neutrino_proto/status/1311742642368253952
https://twitter.com/wavesprotocol/status/1319308791935062020
https://ca.finance.yahoo.com/news/waves-issues-erc-20-collaboration-160000922.html
https://www.businesswire.com/news/home/20201022005325/en/Waves-Issues-ERC-20-for-Collaboration-with-Ethereum-Network

**Comment by vlzhr** [comment]
Hey @xrn! What does the "pending community activity" tag mean?

**Comment by w0utje** [comment]
I think having USDN native support in metamask would be a great addition!

**Review by w0utje — APPROVED** [review]

**Comment by vlzhr** [comment]
@xrn hey Marcin! quick update about USDN: it is already top-11 stablecoin in the market! could it be verified by Metamask?

**Review by xrn — APPROVED** [review]

**Pull request merged**
