### PR TITLE
Adding DiemLibre to MetaMask Crypto-assets

### PR DESCRIPTION
**Pull request by diemlibredlb**
Hello MetaMask,
We are happy about the contributions you are doing to the crypto space.

We, DiemLibre wish to be listed on your list of Crypto assets, this will ease MetaMask users who want to easily add $DLB to their wallet.

Website: diemlibre.org
Etherscan: https://etherscan.io/token/0x87C22615435998D69ACA34889D03155B694a94fc

We hope you grant our request.
Thank you for understanding.

### CODE REVIEW

**Comment by diemlibredlb** [comment]
Here are our Token Trackers both EtherScan and BSCScan

EtherScan: https://etherscan.io/token/0x87C22615435998D69ACA34889D03155B694a94fc
BSCScan: https://bscscan.com/token/0x87c22615435998d69aca34889d03155b694a94fc

We hope they meet up with the number of holders and transactions.

**Comment by xrn** [comment]
Not sure why but your image is broken - I can not display it

**Comment by diemlibredlb** [comment]
Hello @xrn we have fixed the issue.
Please try again.

Thank you for your feedback.

**Comment by diemlibredlb** [comment]
We are sorry for the late reply, this is very unusual of us. 
We have made the necessary modifications.
Please try again and let us know.

**Review by xrn — APPROVED** [review]

**Comment by diemlibredlb** [comment]
Thank you very much for your corporation.
Please we wish to know will our token be available on the search result on MetaMask?

**Comment by xrn** [comment]
We have to release a new version of this repo and then include it MM - this should take ~ 3 weeks

**Pull request merged**
