### PR TITLE
Add Audius

### PR DESCRIPTION
**Pull request by sddioulde**
Token Address : 0x18aAA7115705e8be94bfFEBDE57Af9BFc265B998
Token Name: Audius
Token Decimals: 18
Token Symbol: AUDIO

Website: https://audius.org
GitHub: https://github.com/AudiusProject
Twitter: https://twitter.com/AudiusProject
Discord: https://discord.gg/9SeuwhG7
Etherscan: https://etherscan.io/token/0x18aAA7115705e8be94bfFEBDE57Af9BFc265B998

### CODE REVIEW

**Comment by xrn** [comment]
Hi @sddioulde  - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

**Comment by sddioulde** [comment]
Hey @xrn - Just updated it! Thanks :)

**Comment by xrn** [comment]
Hi @sddioulde - regular icon should have not more than 5Kb - your current one has 144Kb it is not optimal for users. Can you please use a small one?

**Comment by sddioulde** [comment]
Hi @xrn just updated the image again. Thanks

**Review by xrn — APPROVED** [review]

**Pull request merged**
