### PR TITLE
Added JasmyCoin to MetaMask

### PR DESCRIPTION
**Pull request by toktokds01**
JasmyCoin
Website: https://www.jasmy.co.jp/
Etherscan: https://etherscan.io/token/0x7420B4b9a0110cdC71fB720908340C03F9Bc03EC
Github: https://github.com/TokyoToken/JasmyCoin

### CODE REVIEW

**Comment by toktokds01** [comment]
Dear Sir

Thank you for your support.
Is there anything I need to do to be registered in MetaMask?

**Comment by toktokds01** [comment]
https://etherscan.io/token/0x7420B4b9a0110cdC71fB720908340C03F9Bc03EC

The number of JasmyCoin holders has increased dramatically with the listing of Gate.io.
It has also been listed on MXC for some time.
It is our wish to register with Metamask.
Thank you.

https://www.gate.io/trade/JASMY_USDT?k=10
https://www.mxc.com/trade/easy#JASMY_USDT

**Comment by toktokds01** [comment]
We are listed on JUBI, following MXC and Gate.io. 
As a result, the number of holders and transactions has increased further.

Holders:3,010
Transfers:5,810

https://www.jbex.com/exchange/JASMY1/USDT

We look forward to getting approval from you.

**Review by xrn — APPROVED** [review]

**Comment by toktokds01** [comment]
Dear xrn,

I am very grateful for your cooperation.
We look forward to seeing our tokens reflected in the metamask.
Thank you.

**Pull request merged**
