### PR TITLE
Adding new LTO network token (v2)

### PR DESCRIPTION
**Pull request by brunodb3**
LTO Network has migrated to a new ERC20 token, this PR is to add the new token in MetaMask data.

- [Blog Post about token migration](https://blog.ltonetwork.com/new-erc-20-smart-contract/)
- [Old Token: 0x3db6ba6ab6f95efed1a6e794cad492faaabf294d](https://etherscan.io/address/0x3db6ba6ab6f95efed1a6e794cad492faaabf294d)
- [New Token: 0xd01409314acb3b245cea9500ece3f6fd4d70ea30](https://etherscan.io/address/0xd01409314acb3b245cea9500ece3f6fd4d70ea30)

### CODE REVIEW

**Review by xrn — APPROVED** [review]

**Review by xrn — APPROVED** [review]

**Comment by xrn** [comment]
@brunodb3 - unfortunately asset symbol can not be duplicated in entire JSON file

**Review by xrn — APPROVED** [review]

**Comment by brunodb3** [comment]
The tests failed, something about symbols not being able to overlap. Is it not okay to have `XLTO` as old token and `LTO` as new token?

**Comment by brunodb3** [comment]
@xrn can you provide some input on the comment above? I appreciate it :)

**Review by xrn — APPROVED** [review]

**Comment by brunodb3** [comment]
@xrn thanks for merging the PR, but I don't see the new token on Metamask, when searching for `LTO` I only see the old token... If I add new token manually (via custom token), the logo is not correct. Could you help figuring out why that is?

**Comment by xrn** [comment]
This repo release has to be included in MM release. It should be available in next few days

**Comment by brunodb3** [comment]
Okay, thanks for the update :)

**Pull request merged**
