### PR TITLE
New logo for LTO Network

### PR DESCRIPTION
**Pull request by justmvg**
Updated the logo for LTO Network as published on https://blog.ltonetwork.com/brand-refresh-new-logo/

### CODE REVIEW

**Comment by xrn** [comment]
The size of this logo is too big - a regular SVG logo should be <10kB can you please try to improve it?

**Comment by justmvg** [comment]
> 

Seems I cannot compress it more than this, but I'll go for PNG instead in a new PR.

**Comment by xrn** [comment]
SVG format is a requirement and SVG is always smaller than PNG

**Comment by justmvg** [comment]
> SVG format is a requirement and SVG is always smaller than PNG

Thanks for clarifying. I have made the changes for svg now with a smaller size.

**Pull request merged**
