### PR TITLE
Mettalex token

### PR DESCRIPTION
**Pull request by douglasb99**
Mettalex

Team Background:

Humayun Sheikh, CEO- founding investor in DeepMind (acquired by Google).
Toby Simpson, COO- producer of the successful a-life Creatures series of games and a developer at DeepMind.
Thomas Hain — CSO. A Professor at Sheffield University and established scientist in advanced machine learning AI.
The company includes over 50 Full-time Employees.

About:

The Mettalex team is creating a commodities exchange to enable market participants to gain economic exposure to the spot price and derivatives of commodities and other instruments. This will allow hedging of risk for physical holders of the commodity or leveraged positions for speculators. Positions are taken using specially designed ‘position tokens’.

Mettalex is produced by Fetch.ai, and part of the Fetch.ai orgamisation, whose token is already on Metamask.

Contact Information:

Token Price:
Website: https://mettalex.com/
Email: info@mettalex.com
whitepaper: https://mettalex.com/wp-content/uploads/Mettalex-Litepaper_v1.0.pdf
Twitter: https://twitter.com/mettalex
Github: https://github.com/fetchai

### CODE REVIEW

**Comment by douglasb99** [comment]
I changed the image to an svg as per comments

**Comment by xrn** [comment]
@douglasb99 can I ask also for svg logo for FET? Also, I see that the token name is Fetch not FET, could you fix it as well?

**Comment by douglasb99** [comment]
> Fetch

The token is called FET but the company is called FETCH. I will swap that to an svg and update this PR

**Comment by xrn** [comment]
@douglasb99 when I am checking Etherscan data - https://etherscan.io/token/0xaea46A60368A7bD060eec7DF8CBa43b7EF41Ad85 looks like ERC-20 name filed is equal to Fetch I think for end users will be good to have alignment in this area

**Comment by xrn** [comment]
@douglasb99 did you had a chance to take a look on this?

**Comment by douglasb99** [comment]
I have changed name to Fetch and updated pngs to svgs. Thanks, sorry for the delay.

**Comment by xrn** [comment]
@douglasb99 thanks. I will have 1 more ask. I think the white version of Fetch logo will be not visible in Metamask UI - can you use a dark blue one similar to that one from etherscan https://etherscan.io/token/0xaea46A60368A7bD060eec7DF8CBa43b7EF41Ad85 ?

**Comment by douglasb99** [comment]
> @douglasb99 thanks. I will have 1 more ask. I think the white version of Fetch logo will be not visible in Metamask UI - can you use a dark blue one similar to that one from etherscan https://etherscan.io/token/0xaea46A60368A7bD060eec7DF8CBa43b7EF41Ad85 ?
> 
> Same thing for Mettalex logo

I have changed them for the darker logo. If there are any further issues please say.

**Comment by xrn** [comment]
@douglasb99 Seems that Fetch logo is still white.

**Review by xrn — APPROVED** [review]

**Comment by xrn** [comment]
Thx for all updates @douglasb99

**Pull request merged**
