### PR TITLE
Add router protocol token [Etherscan status neutral]

### PR DESCRIPTION
**Pull request by ss-sonic**

### CODE REVIEW

**Comment by xrn** [comment]
Hi @ss-sonic  - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

**Comment by ss-sonic** [comment]
Sure, I will update it shortly.

**Comment by ss-sonic** [comment]
Hi, @xrn updated the logo to SVG format, could you please take a look? Thanks

**Comment by ss-sonic** [comment]
Hi @xrn is there a chance you can expedite the PR merge? 
Thanks

**Review by xrn — APPROVED** [review]

**Comment by ss-sonic** [comment]
@xrn thanks, If I may ask then what's the approx time it takes to get updated on the Metamask plugin?

**Pull request merged**
