### PR TITLE
Add HaloDAO RNBW and xRNBW logo

### PR DESCRIPTION
**Pull request by tracyarciaga**
Add HaloDAO RNBW and xRNBW logo

HaloDAO Protocol is a decentralised application platform designed to provide stablecoins optimised swaps between each other and against other crypto assets via an automated market maker. It also has the function of enabling stablecoin lending markets.

RNBW is the native utility token that is used for: 1) Governance participation to determine how network resources are allocated 2) When actively staked in vesting and voting in governance, it earns a portion of stablecoin profits 3) Collateral for Lending Markets 4) Collateral for AMM liquidity.
xRNBW functions as a vesting token and a claim on underlying RNBW rewards tokens earned by staking LP tokens.

website: https://www.halodao.com/

RNBW address on Ethereum: 0xe94b97b6b43639e238c851a7e693f50033efd75c
xRNBW address on Ethereum: 0x47BE779De87de6580d0548cde80710a93c502405

### CODE REVIEW

**Review by xrn — APPROVED** [review]

**Comment by tracyarciaga** [comment]
hi @xrn May I follow up on merging this branch ? Thanks!

**Comment by xrn** [comment]
@tracyarciaga can you use EIP-55 vesion of both addresses?

**Comment by tracyarciaga** [comment]
> @tracyarciaga can you use EIP-55 vesion of both addresses and solve conflicts?

@xrn - Done. Please merge, thanks!

**Comment by xrn** [comment]
Hi @tracyarciaga - you have to resolve conflicts before I will be able to merge - thanks in advance

**Comment by tracyarciaga** [comment]
> resolve conflicts before I will be able to merge - th

hey @xrn thanks! However, may I know what conflicts are you referring to?

**Comment by tracyarciaga** [comment]
> Hi @tracyarciaga - you have to resolve conflicts before I will be able to merge - thanks in advance

Conflict is resolved. Please merge :) thank you!

**Comment by xrn** [comment]
@tracyarciaga I had to revert this merge - because your JSON is incorrect - decimals are missing and } sign - can you create PR one more time?

**Pull request merged**
