### PR TITLE
Optimize BZR SVG icon

### PR DESCRIPTION
**Pull request by BazaarsBZR**

### CODE REVIEW

**Comment by bazaars-project** [comment]
Untitled-2

**Comment by bazaars-project** [comment]
please add optimised BZR svg logo as the current one is showing distorted in metamask

**Comment by MRabenda** [comment]
Can you rebase plase? You should only update logo without JSON

**Comment by bazaars-project** [comment]
we previously uploaded the icon of our logo to the images folder as an svg file. This is distorted on Metmask Wallets. Could you please advise us the correct format , size and resolution to add

**Comment by bazaars-project** [comment]
> Can you rebase plase? You should only update logo without JSON.
> 
> Also icon which you are proposing is 1:1 with what is already in the repo - https://github.com/MetaMask/contract-metadata/blob/master/images/BZR.svg

This is an optimised version of it

**Comment by MRabenda** [comment]
@bazaars-project may I ask about rebase of this PR? And also can you provide a screenshot which is showing what is currently wrong with your Icon?

**Comment by bazaars-project** [comment]
> @bazaars-project may I ask about rebase of this PR? And also can you provide a screenshot which is showing what is currently wrong with your Icon?

IMG_1747

**Comment by bazaars-project** [comment]
> > @bazaars-project may I ask about rebase of this PR? And also can you provide a screenshot which is showing what is currently wrong with your Icon?
> 
> IMG_1747

token icon is distorted, We reduced the resolution.

**Comment by MRabenda** [comment]
Ok I got this. As you can see https://github.com/MetaMask/contract-metadata/blob/master/contract-map.json#L4153 contract details are already in Json, please update only icon and we should be good to merge

**Comment by bazaars-project** [comment]
We only updated the icon not the Json in this pull request.
Please merge.

**Comment by MRabenda** [comment]
@bazaars-project please review - https://github.com/MetaMask/contract-metadata/pull/1143/files - here is what you are proposing to change in this PR

**Comment by bazaars-project** [comment]
Yes please

**Comment by BazaarsBZR** [comment]
> @bazaars-project please review - https://github.com/MetaMask/contract-metadata/pull/1143/files - here is what you are proposing to change in this PR

is there anything else we need to do, this hasn't been reviewed yet.

**Pull request closed without merging**
