### PR TITLE
Added 1inch.exchange smart contracts and logo

### PR DESCRIPTION
**Pull request by deacix**

### CODE REVIEW

**Comment by deacix** [comment]
Hey @rekmarks! Can you please review asap? 
Thanks a lot!

**Comment by xrn** [comment]
@deacix - can you update please this PR? Please remove addresses not related to ERC token, and use SVG image - I would like to merge it - thanks.

**Comment by MRabenda** [comment]
@deacix is there an option that someone from your team will help here with that SVG image?

**Comment by MRabenda** [comment]
From discord 

```
CHI it's been deprecated on mainnet due to EIP 1559 :(
```

**Pull request closed without merging**
