### PR TITLE
Adding Mysterium Network token

### PR DESCRIPTION
**Pull request by chompomonim**
MYST is a native token of Mysterium Network.

You can find more information about token and project here: https://mysterium.network/token 
Mysterium is being actively developed. You can see activity on GitHub: https://github.com/mysteriumnetwork

### CODE REVIEW

**Comment by xrn** [comment]
Hi @chompomonim  - There is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

Also, I have not idea why but tests were not triggered for that PR - maybe after images changes it will be started

**Comment by chompomonim** [comment]
@xrn I have missed this your comment. Sorry for delay in adding .svg logo.

**Comment by xrn** [comment]
Hi @chompomonim - can you remove png file from this PR?

**Comment by chompomonim** [comment]
.png icon deleted

**Comment by xrn** [comment]
Already added

**Pull request closed without merging**
